-- ASORTA Tickets live support and staff access
create extension if not exists pgcrypto;
create table if not exists public.admin_users(id uuid primary key default gen_random_uuid(),email text not null unique,display_name text,role text not null default 'support',active boolean not null default true,can_support boolean not null default true,can_settings boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.atlas_staff_members(id uuid primary key default gen_random_uuid(),email text not null unique,display_name text,role text not null default 'support',active boolean not null default true,status text not null default 'active',created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.atlas_staff_badges(id uuid primary key default gen_random_uuid(),staff_member_id uuid not null references public.atlas_staff_members(id) on delete cascade,badge text not null,active boolean not null default true,granted_by text,granted_at timestamptz not null default now(),unique(staff_member_id,badge));
create table if not exists public.atlas_staff_audit_logs(id uuid primary key default gen_random_uuid(),staff_member_id uuid references public.atlas_staff_members(id) on delete set null,action text not null,actor_email text,target_email text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.support_conversations(id uuid primary key default gen_random_uuid(),public_token uuid not null unique default gen_random_uuid(),customer_name text,customer_email text not null,subject text,source text,status text not null default 'open' check(status in('open','pending','answered','closed')),assigned_to text,metadata jsonb not null default '{}'::jsonb,last_message_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.support_messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.support_conversations(id) on delete cascade,sender_type text not null check(sender_type in('customer','operator','system')),author_name text,body text not null,is_internal boolean not null default false,internal_kind text,created_at timestamptz not null default now());
create table if not exists public.support_tickets(id uuid primary key default gen_random_uuid(),conversation_id uuid references public.support_conversations(id) on delete cascade,ticket_number text unique default ('SUP-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),name text,email text not null,subject text,message text,source text,status text not null default 'open',priority text not null default 'normal',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.support_conversation_archives(id uuid primary key default gen_random_uuid(),original_conversation_id uuid,public_token uuid,customer_name text,customer_email text,subject text,source text,status text,transcript jsonb not null default '[]'::jsonb,archived_by text,emailed_to_customer boolean not null default false,archived_at timestamptz not null default now());
alter table public.support_conversations enable row level security;alter table public.support_messages enable row level security;alter table public.support_tickets enable row level security;alter table public.support_conversation_archives enable row level security;
