-- ASORTA Woningruil v8.4 — landelijke verhuurderlijst
-- Bron gecontroleerd op 3 september 2026:
-- https://www.ilent.nl/onderwerpen/autoriteit-woningcorporaties/publicaties-cijfers-en-wetgeving-autoriteit-woningcorporaties/actuele-gegevens-woningcorporaties/corporatieregister
--
-- Iedere unieke, actuele corporatienaam uit het ILT-register staat hieronder één keer.
-- Bij acht al gebruikte namen bewaart ASORTA de kortere publieksnaam, zodat bestaande
-- woningkoppelingen en herkenbare namen intact blijven. Deze migratie is herhaalbaar.

with official_provider_names(name) as (
  values
    ('''Stichting Woonplus Schiedam'''),
    ('''Woningstichting Woningbelang'''),
    ('Almelose Woningstichting ''Beter Wonen'''),
    ('Baston Wonen Stichting'),
    ('Bouwvereniging Huis en Hof'),
    ('Brederode Wonen'),
    ('Christelijke Woningstichting De Goede Woning'),
    ('Christelijke Woningstichting Patrimonium'),
    ('Christelijke Woonstichting Patrimonium'),
    ('De Woningraat'),
    ('De Woonplaats'),
    ('deltaWonen'),
    ('Eigen Haard'),
    ('Groen Wonen Vlist'),
    ('Laurentius'),
    ('Ons Huis, Woningstichting'),
    ('Oost West Wonen'),
    ('Portaal'),
    ('R.K. Woningstichting Ons Huis'),
    ('SallandWonen'),
    ('Stichting ''Beter Wonen'''),
    ('Stichting ''Goed Wonen Gemert'''),
    ('Stichting "De Goede Woning"'),
    ('Stichting 3B Wonen'),
    ('Stichting Acantus'),
    ('Stichting Accolade'),
    ('Stichting Actium'),
    ('Stichting Alwel'),
    ('Stichting Antares Woonservice'),
    ('STICHTING ARCADE mensen en wonen'),
    ('Stichting Area'),
    ('Stichting Bazalt Wonen'),
    ('Stichting Beveland Wonen'),
    ('Stichting Bo-Ex ''91'),
    ('Stichting Brabantwonen'),
    ('Stichting Casade'),
    ('Stichting Cazas Wonen (voorheen Stichting GroenWest)'),
    ('Stichting Clavis'),
    ('Stichting de Alliantie'),
    ('Stichting De Huismeesters'),
    ('Stichting De Leeuw van Putten'),
    ('Stichting de Woonmensen'),
    ('Stichting De Woonschakel Westfriesland'),
    ('Stichting Destion'),
    ('Stichting Domesta'),
    ('Stichting Dudok Wonen'),
    ('Stichting Dunavie'),
    ('Stichting DUWO'),
    ('Stichting Dynhus'),
    ('Stichting Eelder Woningbouw'),
    ('Stichting Elan Wonen'),
    ('Stichting Elkien'),
    ('Stichting Fien Wonen'),
    ('Stichting HABION'),
    ('Stichting Havensteder'),
    ('Stichting Hef Wonen'),
    ('Stichting Hof Wonen'),
    ('Stichting Humanitas Huisvesting'),
    ('Stichting HW Wonen'),
    ('Stichting Idealis'),
    ('Stichting IJsseldal Wonen'),
    ('Stichting Intermaris'),
    ('Stichting Jongeren Huisvesting Twente'),
    ('Stichting Jutphaas Wonen'),
    ('Stichting KleurrijkWonen'),
    ('Stichting Krijtland Wonen'),
    ('Stichting L''Escaut Woonservice'),
    ('Stichting Lefier'),
    ('Stichting Lek en Waard Wonen'),
    ('Stichting LEKSTEDEwonen'),
    ('Stichting Leystromen'),
    ('Stichting Maasdelta Groep (MDG)'),
    ('Stichting MaasWonen'),
    ('Stichting Mercatus'),
    ('Stichting Mijande Wonen'),
    ('Stichting Mooiland'),
    ('Stichting Mozaïek Wonen'),
    ('Stichting NabijWonen (voorheen Stichting Heuvelrug Wonen)'),
    ('Stichting Nester'),
    ('Stichting Nijestee'),
    ('Stichting Omnia Wonen'),
    ('Stichting Omthuis (voorheen Stichting Eemland Wonen)'),
    ('Stichting Oost Flevoland Woondiensten'),
    ('Stichting Oosterpoort Wonen'),
    ('Stichting Openbaar Belang'),
    ('Stichting Ouderenhuisvesting Rotterdam'),
    ('Stichting Parteon'),
    ('Stichting PeelrandWonen'),
    ('Stichting Plavei'),
    ('Stichting Poort6'),
    ('Stichting Pré Wonen'),
    ('Stichting ProWonen'),
    ('Stichting QuaWonen'),
    ('Stichting Reggewoon'),
    ('Stichting Rhenam Wonen'),
    ('Stichting Rhiant'),
    ('Stichting Rijnhart Wonen'),
    ('Stichting Rijswijk Wonen'),
    ('Stichting Rondom Wonen'),
    ('Stichting Sité Woondiensten'),
    ('Stichting SSHN'),
    ('Stichting Stadgenoot'),
    ('Stichting Stadlander'),
    ('Stichting Staedion'),
    ('Stichting Stedelink'),
    ('Stichting Studenten Huisvesting'),
    ('Stichting Tablis Wonen'),
    ('Stichting Talis'),
    ('Stichting TBV'),
    ('Stichting Thius'),
    ('Stichting Thuisvester'),
    ('Stichting Thús Wonen'),
    ('Stichting Trivire'),
    ('Stichting Trudo'),
    ('Stichting UWOON'),
    ('Stichting Velison Wonen'),
    ('Stichting Vidomes'),
    ('Stichting Vincio Wonen'),
    ('Stichting Vivare'),
    ('Stichting Viverion'),
    ('Stichting Volkshuisvesting Arnhem'),
    ('Stichting voorheen De Bouwvereniging'),
    ('Stichting Waardwonen'),
    ('Stichting Waterweg Wonen'),
    ('Stichting WBO Wonen'),
    ('Stichting Welbions'),
    ('Stichting Weller Wonen'),
    ('Stichting Wetland Wonen Groep'),
    ('Stichting woCom'),
    ('Stichting Wold en Waard'),
    ('Stichting Wonen Delden'),
    ('Stichting Wonen Limburg'),
    ('Stichting Wonen Noordwest Friesland'),
    ('Stichting Wonen Vierlingsbeek'),
    ('Stichting Wonen Wittem'),
    ('Stichting Wonen Zuid'),
    ('Stichting WonenBreburg'),
    ('Stichting Woningbedrijf Velsen'),
    ('Stichting Woningbeheer De Vooruitgang'),
    ('Stichting Woningbouw Achtkarspelen'),
    ('Stichting Woningcorporatie Het Gooi en Omstreken'),
    ('Stichting Wonion'),
    ('Stichting Woonbedrijf SWS.Hhvl'),
    ('Stichting Woonborg'),
    ('Stichting Woonbron'),
    ('Stichting Wooncompagnie'),
    ('Stichting Wooncompas'),
    ('Stichting Woonconcept'),
    ('Stichting Woondiensten Aarwoude'),
    ('Stichting Woondiensten Enkhuizen'),
    ('Stichting Woonforte'),
    ('Stichting WoonFriesland'),
    ('Stichting Woongoed Middelburg'),
    ('Stichting Woongoed Zeeuws-Vlaanderen'),
    ('Stichting Woongroen (voorheen Stichting Woongoed Zeist)'),
    ('Stichting Woonin (voorheen Stichting Mitros)'),
    ('Stichting Wooninc.'),
    ('Stichting WoonInvest'),
    ('Stichting Woonkracht10'),
    ('Stichting Woonkwartier'),
    ('Stichting Woonopmaat'),
    ('Stichting Woonpalet Zeewolde'),
    ('Stichting Woonpartners'),
    ('Stichting Woonpunt'),
    ('Stichting Woonservice Drenthe'),
    ('Stichting Woonservice IJsselland'),
    ('Stichting Woonstede'),
    ('Stichting Woontij'),
    ('Stichting Woonveste'),
    ('Stichting Woonwaard Noord-Kennemerland'),
    ('Stichting Woonwaarts'),
    ('Stichting Woonwenz'),
    ('Stichting WoonWest (voorheen Stichting Wonen Wateringen)'),
    ('Stichting Woonzorg Nederland'),
    ('Stichting Wormerwonen'),
    ('Stichting WSG'),
    ('Stichting WYwonen (voorheen Stichting MeerWonen)'),
    ('Stichting Zaandams Volkshuisvesting (ZVH)'),
    ('Stichting Zayaz'),
    ('Stichting Zeeuwland'),
    ('Stichting ZOwonen'),
    ('Tiwos, Tilburgse Woonstichting'),
    ('Wassenaarsche Bouwstichting'),
    ('Woningbouwvereniging ''Beter Wonen'''),
    ('Woningbouwvereniging ''Bolnes'''),
    ('Woningbouwvereniging ''Heerjansdam'''),
    ('Woningbouwvereniging ''St. Willibrordus'''),
    ('Woningbouwvereniging Arnemuiden'),
    ('Woningbouwvereniging Bergopwaarts'),
    ('Woningbouwvereniging De Sleutels'),
    ('Woningbouwvereniging Gelderland'),
    ('Woningbouwvereniging Hoek van Holland'),
    ('Woningbouwvereniging Oostzaanse Volkshuisvesting'),
    ('Woningbouwvereniging Poortugaal'),
    ('Woningbouwvereniging Rosehaghe'),
    ('Woningbouwvereniging Samenwerking Slikkerveer'),
    ('Woningstichting ''Wuta'' (Wacht uw tijd af)'),
    ('Woningstichting Anna Paulowna'),
    ('Woningstichting Barneveld'),
    ('Woningstichting Compaen'),
    ('Woningstichting De Goede Woning'),
    ('Woningstichting De Volmacht'),
    ('Woningstichting de Zaligheden'),
    ('Woningstichting Den Helder'),
    ('Woningstichting Domijn'),
    ('Woningstichting GoedeStede'),
    ('Woningstichting Goud Wonen (voorheen Stichting Uithuizer Woningbouw)'),
    ('Woningstichting Haag Wonen'),
    ('Woningstichting HEEMwonen'),
    ('Woningstichting Het Grootslag'),
    ('Woningstichting Heteren'),
    ('Woningstichting Kennemer Wonen'),
    ('Woningstichting Maasdriel'),
    ('Woningstichting Maasvallei Maastricht'),
    ('Woningstichting Meerssen'),
    ('Woningstichting Naarden'),
    ('Woningstichting Nieuwkoop'),
    ('Woningstichting Nijkerk'),
    ('Woningstichting Ons Doel'),
    ('Woningstichting Putten'),
    ('Woningstichting Rentree'),
    ('Woningstichting Ressort Wonen'),
    ('Woningstichting Rochdale'),
    ('Woningstichting Samenwerking Vlaardingen'),
    ('Woningstichting Servatius'),
    ('Woningstichting Sint Antonius van Padua'),
    ('Woningstichting Sint Joseph Almelo'),
    ('Woningstichting SWZ'),
    ('Woningstichting Tubbergen'),
    ('Woningstichting Van Alckmaer voor Wonen'),
    ('Woningstichting Vanhier Wonen'),
    ('Woningstichting Vecht en Omstreken'),
    ('Woningstichting Veenvesters'),
    ('Woningstichting Veluwonen'),
    ('Woningstichting Wageningen (voorheen de Woningstichting)'),
    ('Woningstichting Weststellingwerf'),
    ('Woningstichting Wierden en Borgen'),
    ('Woningstichting Woensdrecht'),
    ('Woningstichting Woonvizier'),
    ('Woningvereniging Woonik (voorheen Woningvereniging Nederweert)'),
    ('Woonbedrijf ieder1'),
    ('Woonmeij'),
    ('Woonpartners Midden-Holland, Stichting voor Bouwen en Beheren'),
    ('Woonstad Rotterdam'),
    ('Woonstichting ''thuis'),
    ('Woonstichting Centrada'),
    ('Woonstichting De Kernen'),
    ('Woonstichting De Marken'),
    ('Woonstichting De Zes Kernen'),
    ('Woonstichting Groninger Huis'),
    ('Woonstichting Hulst'),
    ('Woonstichting JOOST'),
    ('Woonstichting Land van Altena'),
    ('Woonstichting Lieven De Key'),
    ('Woonstichting Patrimonium'),
    ('Woonstichting Stek'),
    ('Woonstichting Triada'),
    ('Woonstichting Valburg'),
    ('Woonstichting VechtHorst'),
    ('Woonstichting Vryleve'),
    ('Woonstichting Zaam Wonen'),
    ('Ymere')
)
insert into public.housing_providers (
  name,
  provider_type,
  source_url,
  last_verified_at,
  verified,
  active,
  updated_at
)
select
  name,
  'housing_corporation',
  'https://www.ilent.nl/onderwerpen/autoriteit-woningcorporaties/publicaties-cijfers-en-wetgeving-autoriteit-woningcorporaties/actuele-gegevens-woningcorporaties/corporatieregister',
  now(),
  true,
  true,
  now()
from official_provider_names
on conflict (name) do update set
  provider_type = excluded.provider_type,
  source_url = excluded.source_url,
  last_verified_at = excluded.last_verified_at,
  verified = true,
  active = true,
  updated_at = now();

-- De Woningzoeker is een officieel woonruimteplatform van meerdere corporaties
-- in West-Overijssel. Het is selecteerbaar om niemand te blokkeren, maar wordt
-- in de interface nadrukkelijk niet als juridische verhuurder aangeduid.
insert into public.housing_providers (
  name,
  provider_type,
  website_url,
  source_url,
  last_verified_at,
  verified,
  active,
  updated_at
)
values (
  'De Woningzoeker',
  'other',
  'https://www.dewoningzoeker.nl/',
  'https://www.dewoningzoeker.nl/',
  now(),
  true,
  true,
  now()
)
on conflict (name) do update set
  provider_type = excluded.provider_type,
  website_url = excluded.website_url,
  source_url = excluded.source_url,
  last_verified_at = excluded.last_verified_at,
  verified = true,
  active = true,
  updated_at = now();

-- Universele uitweg voor particuliere, gemeentelijke of nog ontbrekende verhuurders.
insert into public.housing_providers (
  name,
  provider_type,
  verified,
  active,
  updated_at
)
values ('Andere verhuurder', 'other', false, true, now())
on conflict (name) do update set
  provider_type = 'other',
  active = true,
  updated_at = now();

select
  count(*) filter (where provider_type = 'housing_corporation' and active) as actieve_corporaties,
  count(*) filter (where active) as totaal_actieve_keuzes
from public.housing_providers;

