import type { SupabaseClient } from '@supabase/supabase-js'
import { supabase } from '@/lib/supabase'
import { getShopifyConfig, shopifyGidToLegacyId } from '@/lib/shopify/client'
import { products as staticProducts } from '@/lib/products'

type CheckoutCartItem = {
  slug: string
  rawSlug: string
  qty: number
  variantSku?: string
  shopifyVariantId?: string
  shopifyVariantLegacyId?: string
}

type ProductRow = Record<string, any>

function normalizeQty(value: unknown) {
  const qty = Math.floor(Number(value || 1))
  return Math.min(20, Math.max(1, Number.isFinite(qty) ? qty : 1))
}

function safeDecode(value: string) {
  try {
    return decodeURIComponent(value)
  } catch {
    return value
  }
}

/**
 * Cart items from older ASORTA/CJ builds sometimes stored a variant marker inside
 * the slug, for example:
 *
 *   product-slug__14:771#Style 1
 *
 * Supabase stores only the base product slug, while Shopify checkout needs the
 * Shopify variant id. This normalizer keeps checkout backward-compatible with
 * older localStorage carts and avoids requiring the exact full cart key.
 */
export function normalizeCheckoutProductSlug(value: unknown) {
  let slug = safeDecode(String(value || '').trim())

  if (!slug) return ''

  // Accept accidental product URLs/paths as well as raw slugs.
  slug = slug.replace(/^https?:\/\/[^/]+/i, '')
  slug = slug.split('?')[0] || slug
  slug = slug.split('#')[0] || slug
  slug = slug.replace(/^\/+/g, '')
  slug = slug.replace(/^products\//i, '')
  slug = slug.replace(/^product\//i, '')

  // Strip legacy variant suffixes generated by previous cart keys.
  slug = slug.split('__')[0] || slug
  slug = slug.split('::')[0] || slug

  return slug.trim().replace(/\/+$/g, '').toLowerCase()
}

function normalizeVariantLegacyId(value: unknown) {
  const raw = String(value || '').trim()
  if (!raw) return ''
  return shopifyGidToLegacyId(raw) || raw
}

function normalizeDiscountCode(value: unknown) {
  return String(value || '')
    .trim()
    .replace(/\s+/g, '')
    .replace(/[^A-Z0-9_-]/gi, '')
    .toUpperCase()
    .slice(0, 80)
}

function normalizeItem(item: any): CheckoutCartItem | null {
  const rawSlug = String(item?.slug || item?.productSlug || item?.handle || '').trim()
  const slug = normalizeCheckoutProductSlug(rawSlug)
  const directVariantId = String(item?.shopifyVariantId || item?.shopify_variant_id || '').trim()
  const directLegacyId = normalizeVariantLegacyId(
    item?.shopifyVariantLegacyId || item?.shopify_variant_legacy_id || directVariantId,
  )

  if (!slug && !directLegacyId) return null

  return {
    slug,
    rawSlug: rawSlug || slug,
    qty: normalizeQty(item?.qty || item?.quantity),
    variantSku: String(item?.variantSku || item?.sku || item?.variant_sku || '').trim(),
    shopifyVariantId: directVariantId,
    shopifyVariantLegacyId: directLegacyId,
  }
}

function normalizeItems(input: unknown) {
  if (!Array.isArray(input)) return []
  return input.map(normalizeItem).filter(Boolean) as CheckoutCartItem[]
}

function parseJsonArray<T>(value: unknown, fallback: T[] = []) {
  if (Array.isArray(value)) return value as T[]
  if (typeof value === 'string' && value.trim()) {
    try {
      const parsed = JSON.parse(value)
      return Array.isArray(parsed) ? (parsed as T[]) : fallback
    } catch {
      return fallback
    }
  }
  return fallback
}

async function loadProducts(client: SupabaseClient | null, slugs: string[]) {
  const normalizedSlugs = Array.from(new Set(slugs.map(normalizeCheckoutProductSlug).filter(Boolean)))

  if (!client) {
    return staticProducts.filter((product) => normalizedSlugs.includes(product.slug)).map((product): ProductRow => ({
      slug: product.slug,
      name: product.name,
      status: 'active',
      price: product.price,
      variants: product.variants || [],
    }))
  }

  if (!normalizedSlugs.length) return [] as ProductRow[]

  const { data, error } = await client
    .from('products')
    .select('slug,name,status,price,shopify_product_id,shopify_variant_id,shopify_variant_legacy_id,variants')
    .in('slug', normalizedSlugs)
    .in('status', ['active', 'launch'])

  if (error) throw new Error(error.message)
  return (data || []) as ProductRow[]
}

function findVariant(row: ProductRow, item: CheckoutCartItem) {
  const variants = parseJsonArray<Record<string, any>>(row.variants, [])
  if (!variants.length) return undefined

  return variants.find((variant) => {
    const candidates = [
      variant.sku,
      variant.variantId,
      variant.shopifyVariantId,
      variant.shopify_variant_id,
      variant.shopifyVariantLegacyId,
      variant.shopify_variant_legacy_id,
    ].map((value) => normalizeVariantLegacyId(value) || String(value || '').trim()).filter(Boolean)

    return [item.variantSku, item.shopifyVariantId, item.shopifyVariantLegacyId]
      .map((value) => normalizeVariantLegacyId(value) || String(value || '').trim())
      .filter(Boolean)
      .some((value) => candidates.includes(value))
  }) || variants[0]
}

function variantLegacyId(row: ProductRow | undefined, item: CheckoutCartItem) {
  if (item.shopifyVariantLegacyId) return item.shopifyVariantLegacyId
  if (item.shopifyVariantId) return shopifyGidToLegacyId(item.shopifyVariantId)
  if (!row) return ''

  const variant = findVariant(row, item)
  const fromVariant =
    variant?.shopifyVariantLegacyId ||
    variant?.shopify_variant_legacy_id ||
    shopifyGidToLegacyId(variant?.shopifyVariantId || variant?.shopify_variant_id || variant?.variantId)
  const fromProduct = row.shopify_variant_legacy_id || shopifyGidToLegacyId(row.shopify_variant_id)

  return String(fromVariant || fromProduct || '').trim()
}

function mergeLines(lines: Array<{ variantId: string; quantity: number }>) {
  const merged = new Map<string, number>()
  for (const line of lines) {
    merged.set(line.variantId, (merged.get(line.variantId) || 0) + line.quantity)
  }
  return Array.from(merged.entries()).map(([variantId, quantity]) => ({ variantId, quantity }))
}

function buildCheckoutUrl(lines: Array<{ variantId: string; quantity: number }>, email?: string, discountCode?: unknown) {
  const { checkoutDomain } = getShopifyConfig()
  if (!checkoutDomain) throw new Error('SHOPIFY_STORE_DOMAIN ontbreekt.')

  const path = lines.map((line) => `${encodeURIComponent(line.variantId)}:${line.quantity}`).join(',')
  const url = new URL(`https://${checkoutDomain}/cart/${path}`)
  url.searchParams.set('utm_source', 'asorta')
  url.searchParams.set('utm_medium', 'custom_frontend')
  url.searchParams.set('utm_campaign', 'paypal_shopify_checkout')
  url.searchParams.set('attributes[asorta_source]', 'custom_frontend')
  url.searchParams.set('attributes[fulfillment]', 'dsers')
  const discount = normalizeDiscountCode(discountCode)
  if (discount) url.searchParams.set('discount', discount)
  if (email && email.includes('@')) url.searchParams.set('checkout[email]', email)
  return url.toString()
}

export async function createShopifyCheckoutRedirect(input: { items: unknown; email?: string; discountCode?: unknown; client?: SupabaseClient | null }) {
  const items = normalizeItems(input.items)
  if (!items.length) throw new Error('Cart is leeg.')

  const slugs = Array.from(new Set(items.map((item) => item.slug).filter(Boolean)))
  const rows = await loadProducts(input.client ?? supabase, slugs)
  const rowBySlug = new Map(rows.map((row) => [normalizeCheckoutProductSlug(row.slug), row]))

  const lines = [] as Array<{ variantId: string; quantity: number }>
  const missing = [] as string[]

  for (const item of items) {
    const row = item.slug ? rowBySlug.get(item.slug) : undefined
    const id = variantLegacyId(row, item)

    // If the cart already carries a Shopify variant id, do not block checkout on
    // an old/over-specific slug. Shopify remains the source of truth for the
    // actual product availability and final checkout price.
    if (!row && !id) {
      missing.push(`${item.rawSlug}: product niet gevonden of niet actief`)
      continue
    }

    if (!id) {
      missing.push(`${item.rawSlug}: Shopify variant ID ontbreekt. Run Shopify sync opnieuw en controleer of productvarianten uit Shopify komen.`)
      continue
    }

    lines.push({ variantId: id, quantity: item.qty })
  }

  if (missing.length) {
    throw new Error(`Checkout kan niet starten: ${missing.join('; ')}`)
  }

  const mergedLines = mergeLines(lines)
  return {
    checkoutUrl: buildCheckoutUrl(mergedLines, input.email, input.discountCode),
    lineCount: mergedLines.length,
    itemCount: mergedLines.reduce((sum, line) => sum + line.quantity, 0),
  }
}
