import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { markNotificationsRead } from '@/app/housing/actions'
import { Bell, CheckCheck } from 'lucide-react'

export const dynamic='force-dynamic'
export const metadata={title:'Meldingen'}
export default async function Notifications(){const s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)redirect('/login?next=/notifications');const{data:items=[]}=await s.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);return <main className="mx-auto min-h-screen max-w-4xl px-4 py-12 sm:px-5"><div className="flex items-end justify-between gap-4"><div><p className="kicker">Mijn Asorta</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Meldingen</h1></div>{items?.some((x:any)=>!x.read_at)&&<form action={markNotificationsRead}><button className="btn-secondary gap-2"><CheckCheck size={17}/> Alles gelezen</button></form>}</div>{items?.length?<div className="mt-8 grid gap-3">{items.map((x:any)=><Link key={x.id} href={x.href||'/account'} className={`rounded-2xl border p-5 transition hover:border-white/25 ${x.read_at?'border-white/10 bg-white/[.025]':'border-[#b8ff5a]/22 bg-[#b8ff5a]/[.055]'}`}><div className="flex gap-4"><span className={`mt-1 grid h-9 w-9 shrink-0 place-items-center rounded-full ${x.read_at?'bg-white/7 text-white/35':'bg-[#b8ff5a] text-black'}`}><Bell size={17}/></span><div><h2 className="font-black">{x.title}</h2><p className="mt-2 text-sm leading-6 text-white/48">{x.body}</p><time className="mt-3 block text-xs text-white/30">{new Date(x.created_at).toLocaleString('nl-NL')}</time></div></div></Link>)}</div>:<div className="mt-8 rounded-[2rem] border border-white/10 bg-white/[.035] p-10 text-center"><Bell size={42} className="mx-auto text-white/20"/><h2 className="mt-5 text-2xl font-black">Nog geen meldingen</h2><p className="mt-3 text-white/45">Nieuwe matches, berichten en ruilupdates verschijnen hier.</p></div>}</main>}
