import Link from 'next/link'
import { Ban, Banknote, HousePlus, Search, ShieldCheck, UserCog, Users } from 'lucide-react'
import { assertAtlasPermission, hasAtlasPermission } from '@/lib/atlas-auth'
import { activateCashListing, activateCashSearchPass, setAtlasUserBlock, updateAtlasUser } from './actions'

export const dynamic='force-dynamic'
export const metadata={title:'Gebruikers | Atlas',robots:{index:false,follow:false}}

export default async function AtlasUsers({searchParams}:{searchParams:Promise<{q?:string;saved?:string;error?:string}>}){
  const p=await searchParams,{admin,staff}=await assertAtlasPermission('users','/atlas/users'),query=String(p.q||'').trim().toLocaleLowerCase('nl-NL'),canManagePayments=hasAtlasPermission(staff,'payments')
  const[profileResult,searchResult,listingResult,passResult,authResult]=await Promise.all([
    admin.from('profiles').select('id,user_number,system_username,custom_display_name,display_name_mode,phone,onboarding_completed,blocked_at,block_reason,last_active_at,created_at').order('created_at',{ascending:false}).limit(1000),
    admin.from('search_profiles').select('user_id,status').limit(1000),
    admin.from('listings').select('id,user_id,status,city,created_at').order('created_at',{ascending:false}).limit(5000),
    admin.from('access_passes').select('id,user_id,status,starts_at,expires_at,payment_id').limit(5000),
    admin.auth.admin.listUsers({page:1,perPage:1000}),
  ])
  const loadError=[profileResult.error,searchResult.error,listingResult.error,passResult.error,authResult.error].find(Boolean)?.message||''
  const emails=new Map((authResult.data?.users||[]).map((user:any)=>[user.id,user.email||'']))
  const searches=new Map((searchResult.data||[]).map((profile:any)=>[profile.user_id,profile]))
  const listingCounts=new Map<string,number>()
  for(const listing of listingResult.data||[])listingCounts.set(listing.user_id,(listingCounts.get(listing.user_id)||0)+1)
  const unpaidListings=new Map<string,any>()
  for(const listing of listingResult.data||[])if(['draft','pending_payment'].includes(listing.status)&&!unpaidListings.has(listing.user_id))unpaidListings.set(listing.user_id,listing)
  const activePasses=new Map((passResult.data||[]).filter((pass:any)=>pass.status==='active'&&new Date(pass.expires_at).getTime()>Date.now()).map((pass:any)=>[pass.user_id,pass]))
  const profiles=(profileResult.data||[]).filter((profile:any)=>{
    if(!query)return true
    return [profile.system_username,profile.custom_display_name,emails.get(profile.id),String(profile.user_number)].some((value)=>String(value||'').toLocaleLowerCase('nl-NL').includes(query))
  })
  return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-5">
    <div className="flex items-end justify-between gap-4"><div><p className="kicker">Atlas beheer</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Gebruikers</h1><p className="mt-3 text-white/45">Pas alleen gegevens aan die een gebruiker niet zelf kan herstellen of wanneer support daar aanleiding voor geeft.</p></div><Link href="/atlas" className="btn-secondary">Terug</Link></div>
    {p.saved&&<Notice good>{p.saved==='cash-pass'?'Contante betaling vastgelegd en zoekpas bijgewerkt.':p.saved==='cash-listing'?'Contante betaling vastgelegd en woning geactiveerd.':'Gebruiker bijgewerkt.'}</Notice>}{p.error&&<Notice>{p.error}</Notice>}{loadError&&<Notice>Gebruikers konden niet volledig worden geladen: {loadError}</Notice>}
    <form className="mt-7 flex gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="relative flex-1"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-white/30" size={18}/><input name="q" defaultValue={p.q||''} className="field pl-11" placeholder="Zoek op Ruiler-ID, naam of e-mail"/></div><button className="btn-primary">Zoeken</button></form>
    <div className="mt-4 flex items-center justify-between text-sm text-white/40"><span>{profiles.length} gebruiker{profiles.length===1?'':'s'} gevonden</span>{p.q&&<Link href="/atlas/users" className="font-bold text-[#b8ff5a]">Zoekopdracht wissen</Link>}</div>
    <section className="mt-6 grid gap-5">{profiles.map((profile:any)=>{
      const email=emails.get(profile.id)||'E-mail niet beschikbaar',searchProfile=searches.get(profile.id),listingCount=listingCounts.get(profile.id)||0,activePass=activePasses.get(profile.id) as any,unpaidListing=unpaidListings.get(profile.id)
      return <details key={profile.id} className="card rounded-[1.7rem]"><summary className="flex cursor-pointer list-none flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#b8ff5a]/10 text-[#b8ff5a]"><Users size={19}/></span><div><strong className="text-lg">{display(profile)}</strong><p className="mt-1 text-sm text-white/40">{profile.system_username} · {email}</p></div></div><div className="flex flex-wrap items-center gap-2"><Pill text={profile.blocked_at?'Geblokkeerd':'Actief'} bad={Boolean(profile.blocked_at)}/><Pill text={`${listingCount} woning${listingCount===1?'':'en'}`}/><Pill text={activePass?`Zoekpas t/m ${dateOnly(activePass.expires_at)}`:'Geen zoekpas'}/></div></summary>
        <div className="border-t border-white/10 p-5"><form action={updateAtlasUser} className="grid gap-4"><input type="hidden" name="user_id" value={profile.id}/><input type="hidden" name="q" value={p.q||''}/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="label"><span>Getoonde naam</span><select name="display_name_mode" defaultValue={profile.display_name_mode} className="field"><option value="system">{profile.system_username}</option><option value="custom">Eigen weergavenaam</option></select></label><label className="label"><span>Eigen weergavenaam</span><input name="custom_display_name" defaultValue={profile.custom_display_name||''} className="field" maxLength={30}/></label><label className="label"><span>Telefoonnummer</span><input name="phone" defaultValue={profile.phone||''} className="field" maxLength={30}/></label><label className="label"><span>Zoekprofiel</span><select name="search_status" defaultValue={searchProfile?.status||''} className="field" disabled={!searchProfile}><option value="">Niet aangemaakt</option><option value="active">Actief</option><option value="paused">Gepauzeerd</option></select></label></div><div className="flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="onboarding_completed" defaultChecked={profile.onboarding_completed} className="accent-[#b8ff5a]"/>Onboarding afgerond</label><span className="text-xs text-white/35">Laatst actief: {date(profile.last_active_at)} · Aangemaakt: {date(profile.created_at)}</span><button className="btn-primary ml-auto gap-2"><UserCog size={16}/> Profiel opslaan</button></div></form>
        <div className="mt-5 grid gap-4 border-t border-white/10 pt-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2"><Banknote className="text-[#b8ff5a]" size={19}/><h3 className="font-black">Zoekpas</h3></div><p className="mt-3 text-sm leading-6 text-white/48">{activePass?<>Actief tot <strong className="text-white">{dateOnly(activePass.expires_at)}</strong>. Een nieuwe contante betaling verlengt vanaf deze einddatum.</>:<>Niet actief. Na bevestiging start de pas direct en is deze 365 dagen geldig.</>}</p></div>{canManagePayments?(profile.blocked_at?<div className="rounded-2xl border border-red-400/20 bg-red-500/[.06] p-4 text-sm text-red-100">Deblokkeer dit account voordat je een zoekpas activeert.</div>:<form action={activateCashSearchPass} className="grid gap-3 rounded-2xl border border-[#b8ff5a]/20 bg-[#b8ff5a]/[.045] p-4 sm:grid-cols-[1fr_auto]"><input type="hidden" name="user_id" value={profile.id}/><input type="hidden" name="q" value={p.q||''}/><label className="label"><span>Notitie of kassabonnummer (optioneel)</span><input name="payment_note" className="field" maxLength={500} placeholder="Bijv. contant ontvangen aan balie"/></label><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input type="checkbox" name="cash_received" required className="accent-[#b8ff5a]"/>Ik bevestig dat €5 contant is ontvangen.</label><p className="text-xs leading-5 text-white/38">Dit wordt als betaalde contante transactie vastgelegd in Atlas en in het auditlog.</p><button className="btn-primary gap-2 self-end"><Banknote size={16}/>{activePass?'Verleng 1 jaar':'Activeer 1 jaar'}</button></form>):<div className="rounded-2xl border border-white/10 p-4 text-sm leading-6 text-white/42">Het Atlas-recht “Betalingen” is nodig om een contante zoekpas te activeren.</div>}</div>
        <div className="mt-5 grid gap-4 border-t border-white/10 pt-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2"><HousePlus className="text-[#b8ff5a]" size={19}/><h3 className="font-black">Woningplaatsing</h3></div><p className="mt-3 text-sm leading-6 text-white/48">{unpaidListing?<>De woning in <strong className="text-white">{unpaidListing.city}</strong> wacht nog op de eenmalige betaling van €2.</>:<>Er staat geen woning klaar die nog op de plaatsingsbetaling wacht.</>}</p></div>{unpaidListing&&canManagePayments?(profile.blocked_at?<div className="rounded-2xl border border-red-400/20 bg-red-500/[.06] p-4 text-sm text-red-100">Deblokkeer dit account voordat je de woning activeert.</div>:<form action={activateCashListing} className="grid gap-3 rounded-2xl border border-[#b8ff5a]/20 bg-[#b8ff5a]/[.045] p-4 sm:grid-cols-[1fr_auto]"><input type="hidden" name="listing_id" value={unpaidListing.id}/><input type="hidden" name="q" value={p.q||''}/><label className="label"><span>Notitie of kassabonnummer (optioneel)</span><input name="payment_note" className="field" maxLength={500} placeholder="Bijv. contant ontvangen aan balie"/></label><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input type="checkbox" name="cash_received" required className="accent-[#b8ff5a]"/>Ik bevestig dat €2 contant is ontvangen.</label><p className="text-xs leading-5 text-white/38">De woning wordt direct actief, doet mee met matching en moet na 90 dagen opnieuw worden bevestigd.</p><button className="btn-primary gap-2 self-end"><HousePlus size={16}/>Activeer woning</button></form>):unpaidListing&&!canManagePayments?<div className="rounded-2xl border border-white/10 p-4 text-sm leading-6 text-white/42">Het Atlas-recht “Betalingen” is nodig om een contante woningplaatsing te activeren.</div>:<div className="rounded-2xl border border-white/10 p-4 text-sm leading-6 text-white/35">Zodra deze gebruiker een woning heeft geplaatst en nog niet heeft betaald, verschijnt hier de €2-activering.</div>}</div>
        <div className="mt-5 border-t border-white/10 pt-5">{profile.blocked_at?<form action={setAtlasUserBlock} className="flex flex-wrap items-center gap-3"><input type="hidden" name="user_id" value={profile.id}/><input type="hidden" name="q" value={p.q||''}/><input type="hidden" name="blocked" value="false"/><p className="mr-auto text-sm text-red-200"><Ban className="mr-2 inline" size={16}/>{profile.block_reason||'Account is geblokkeerd.'}</p><button className="btn-secondary">Account deblokkeren</button></form>:<form action={setAtlasUserBlock} className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input type="hidden" name="user_id" value={profile.id}/><input type="hidden" name="q" value={p.q||''}/><input type="hidden" name="blocked" value="true"/><input name="reason" className="field" placeholder="Reden voor blokkade"/><input name="confirmation" className="field" placeholder="Typ BLOKKEREN"/><button className="btn-secondary gap-2 text-red-100"><Ban size={16}/> Account blokkeren</button></form>}</div></div>
      </details>
    })}{!profiles.length&&<div className="card rounded-[1.7rem] p-10 text-center"><ShieldCheck className="mx-auto text-[#b8ff5a]"/><h2 className="mt-4 text-2xl font-black">Geen gebruikers gevonden</h2><p className="mt-2 text-white/42">Controleer de zoekterm of wis de zoekopdracht.</p></div>}</section>
  </main>
}

function display(profile:any){return profile.display_name_mode==='custom'&&profile.custom_display_name?profile.custom_display_name:profile.system_username}
function date(value:string|null){if(!value)return '—';return new Date(value).toLocaleString('nl-NL')}
function dateOnly(value:string){return new Date(value).toLocaleDateString('nl-NL')}
function Pill({text,bad=false}:{text:string;bad?:boolean}){return <span className={`rounded-full px-3 py-1 text-xs font-black ${bad?'bg-red-500/10 text-red-200':'border border-white/10 bg-white/[.035] text-white/52'}`}>{text}</span>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm font-bold ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
