import Link from 'next/link'
import { Ban, Search, ShieldCheck, UserCog, Users } from 'lucide-react'
import { assertAtlasPermission } from '@/lib/atlas-auth'
import { setAtlasUserBlock, updateAtlasUser } from './actions'

export const dynamic='force-dynamic'
export const metadata={title:'Gebruikers | Atlas',robots:{index:false,follow:false}}

export default async function AtlasUsers({searchParams}:{searchParams:Promise<{q?:string;saved?:string;error?:string}>}){
  const p=await searchParams,{admin}=await assertAtlasPermission('users','/atlas/users'),query=String(p.q||'').trim().toLocaleLowerCase('nl-NL')
  const[{data:profileRows},{data:authData}]=await Promise.all([
    admin.from('profiles').select('id,user_number,system_username,custom_display_name,display_name_mode,phone,onboarding_completed,blocked_at,block_reason,last_active_at,created_at,search_profiles(id,status),listings(id,status,city),access_passes(status,expires_at)').order('created_at',{ascending:false}).limit(1000),
    admin.auth.admin.listUsers({page:1,perPage:1000}),
  ])
  const emails=new Map((authData?.users||[]).map((user:any)=>[user.id,user.email||''])),profiles=(profileRows||[]).filter((profile:any)=>{
    if(!query)return true
    return [profile.system_username,profile.custom_display_name,emails.get(profile.id),String(profile.user_number)].some((value)=>String(value||'').toLocaleLowerCase('nl-NL').includes(query))
  })
  return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-5">
    <div className="flex items-end justify-between gap-4"><div><p className="kicker">Atlas beheer</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Gebruikers</h1><p className="mt-3 text-white/45">Pas alleen gegevens aan die een gebruiker niet zelf kan herstellen of wanneer support daar aanleiding voor geeft.</p></div><Link href="/atlas" className="btn-secondary">Terug</Link></div>
    {p.saved&&<Notice good>Gebruiker bijgewerkt.</Notice>}{p.error&&<Notice>{p.error}</Notice>}
    <form className="mt-7 flex gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="relative flex-1"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-white/30" size={18}/><input name="q" defaultValue={p.q||''} className="field pl-11" placeholder="Zoek op Ruiler-ID, naam of e-mail"/></div><button className="btn-primary">Zoeken</button></form>
    <div className="mt-4 flex items-center justify-between text-sm text-white/40"><span>{profiles.length} gebruiker{profiles.length===1?'':'s'} gevonden</span>{p.q&&<Link href="/atlas/users" className="font-bold text-[#b8ff5a]">Zoekopdracht wissen</Link>}</div>
    <section className="mt-6 grid gap-5">{profiles.map((profile:any)=>{
      const email=emails.get(profile.id)||'E-mail niet beschikbaar',searchProfile=Array.isArray(profile.search_profiles)?profile.search_profiles[0]:profile.search_profiles,listings=profile.listings||[],activePass=(profile.access_passes||[]).find((pass:any)=>pass.status==='active')
      return <details key={profile.id} className="card rounded-[1.7rem]"><summary className="flex cursor-pointer list-none flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#b8ff5a]/10 text-[#b8ff5a]"><Users size={19}/></span><div><strong className="text-lg">{display(profile)}</strong><p className="mt-1 text-sm text-white/40">{profile.system_username} · {email}</p></div></div><div className="flex flex-wrap items-center gap-2"><Pill text={profile.blocked_at?'Geblokkeerd':'Actief'} bad={Boolean(profile.blocked_at)}/><Pill text={`${listings.length} woning${listings.length===1?'':'en'}`}/><Pill text={activePass?'Zoekpas actief':'Geen zoekpas'}/></div></summary>
        <div className="border-t border-white/10 p-5"><form action={updateAtlasUser} className="grid gap-4"><input type="hidden" name="user_id" value={profile.id}/><input type="hidden" name="q" value={p.q||''}/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="label"><span>Getoonde naam</span><select name="display_name_mode" defaultValue={profile.display_name_mode} className="field"><option value="system">{profile.system_username}</option><option value="custom">Eigen weergavenaam</option></select></label><label className="label"><span>Eigen weergavenaam</span><input name="custom_display_name" defaultValue={profile.custom_display_name||''} className="field" maxLength={30}/></label><label className="label"><span>Telefoonnummer</span><input name="phone" defaultValue={profile.phone||''} className="field" maxLength={30}/></label><label className="label"><span>Zoekprofiel</span><select name="search_status" defaultValue={searchProfile?.status||''} className="field" disabled={!searchProfile}><option value="">Niet aangemaakt</option><option value="active">Actief</option><option value="paused">Gepauzeerd</option></select></label></div><div className="flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="onboarding_completed" defaultChecked={profile.onboarding_completed} className="accent-[#b8ff5a]"/>Onboarding afgerond</label><span className="text-xs text-white/35">Laatst actief: {date(profile.last_active_at)} · Aangemaakt: {date(profile.created_at)}</span><button className="btn-primary ml-auto gap-2"><UserCog size={16}/> Profiel opslaan</button></div></form>
        <div className="mt-5 border-t border-white/10 pt-5">{profile.blocked_at?<form action={setAtlasUserBlock} className="flex flex-wrap items-center gap-3"><input type="hidden" name="user_id" value={profile.id}/><input type="hidden" name="q" value={p.q||''}/><input type="hidden" name="blocked" value="false"/><p className="mr-auto text-sm text-red-200"><Ban className="mr-2 inline" size={16}/>{profile.block_reason||'Account is geblokkeerd.'}</p><button className="btn-secondary">Account deblokkeren</button></form>:<form action={setAtlasUserBlock} className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input type="hidden" name="user_id" value={profile.id}/><input type="hidden" name="q" value={p.q||''}/><input type="hidden" name="blocked" value="true"/><input name="reason" className="field" placeholder="Reden voor blokkade"/><input name="confirmation" className="field" placeholder="Typ BLOKKEREN"/><button className="btn-secondary gap-2 text-red-100"><Ban size={16}/> Account blokkeren</button></form>}</div></div>
      </details>
    })}{!profiles.length&&<div className="card rounded-[1.7rem] p-10 text-center"><ShieldCheck className="mx-auto text-[#b8ff5a]"/><h2 className="mt-4 text-2xl font-black">Geen gebruikers gevonden</h2><p className="mt-2 text-white/42">Controleer de zoekterm of wis de zoekopdracht.</p></div>}</section>
  </main>
}

function display(profile:any){return profile.display_name_mode==='custom'&&profile.custom_display_name?profile.custom_display_name:profile.system_username}
function date(value:string|null){if(!value)return '—';return new Date(value).toLocaleString('nl-NL')}
function Pill({text,bad=false}:{text:string;bad?:boolean}){return <span className={`rounded-full px-3 py-1 text-xs font-black ${bad?'bg-red-500/10 text-red-200':'border border-white/10 bg-white/[.035] text-white/52'}`}>{text}</span>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm font-bold ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
