import Image from 'next/image'
import Link from 'next/link'
import HomeCard from '@/components/HomeCard'
import { getPublicHomes } from '@/lib/housing-data'
import { ArrowRight, BadgeCheck, Building2, Check, Search, ShieldCheck, Sparkles, UsersRound } from 'lucide-react'

export const dynamic='force-dynamic'
export default async function Home(){const homes=(await getPublicHomes()).slice(0,3);return <main>
  <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_24%,rgba(184,255,90,.14),transparent_28%),radial-gradient(circle_at_18%_62%,rgba(77,150,255,.09),transparent_24%)]"/><div className="relative mx-auto grid min-h-[690px] max-w-7xl items-center gap-12 px-4 py-16 sm:px-5 lg:grid-cols-[1.04fr_.96fr]">
    <div><div className="inline-flex items-center gap-2 rounded-full border border-[#b8ff5a]/25 bg-[#b8ff5a]/[.07] px-4 py-2 text-xs font-black text-[#d5ffa7]"><BadgeCheck size={15}/> Woningruil die aan beide kanten klopt</div><h1 className="mt-7 max-w-4xl text-balance text-5xl font-black leading-[.94] tracking-[-.055em] sm:text-6xl lg:text-7xl">Jouw woning gezocht. <span className="text-[#b8ff5a]">Jouw nieuwe thuis gevonden.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/58">Plaats je huurwoning, vertel waar je naartoe wilt en ontvang automatisch wederzijdse matches. Geen eindeloos reageren op woningen die niet terug willen ruilen.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/place-home" className="btn-primary gap-2 px-6 py-4">Plaats je woning <ArrowRight size={18}/></Link><Link href="/homes" className="btn-secondary gap-2 px-6 py-4"><Search size={18}/> Bekijk woningen</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-white/46"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-[#b8ff5a]"/>Exact adres blijft privé</span><span className="flex items-center gap-2"><UsersRound size={17} className="text-[#b8ff5a]"/>Anoniem starten</span><span className="flex items-center gap-2"><Sparkles size={17} className="text-[#b8ff5a]"/>Slim gematcht</span></div></div>
    <div className="relative mx-auto w-full max-w-[560px]"><div className="absolute -inset-10 rounded-full bg-[#b8ff5a]/10 blur-3xl"/><div className="relative overflow-hidden rounded-[2.2rem] border border-white/15 bg-[#0b1118] p-3 shadow-[0_40px_140px_rgba(0,0,0,.65)]"><div className="relative aspect-[16/10] overflow-hidden rounded-[1.55rem]"><Image src="/asorta-home-swap-hero.png" alt="Nederlandse huurwoningen verbonden voor woningruil" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-5"><span className="status-pill">Wederzijdse woningruil</span><div className="mt-3 flex items-end justify-between gap-3"><div><strong className="text-2xl">Jullie woonwensen verbinden</strong><p className="mt-1 text-sm text-white/58">Asorta controleert of beide woningen over en weer passen</p></div><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#b8ff5a] text-black"><Check size={20} strokeWidth={3}/></span></div></div></div></div></div>
  </div></section>
  <section className="mx-auto max-w-7xl px-4 py-16 sm:px-5 sm:py-20"><div className="flex items-end justify-between gap-5"><div><p className="kicker">Bekijk het aanbod</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Woningen die willen ruilen</h2></div>{homes.length>0&&<Link href="/homes" className="hidden items-center gap-2 text-sm font-black text-white/55 hover:text-white sm:flex">Alles bekijken <ArrowRight size={16}/></Link>}</div>{homes.length>0?<div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{homes.map(home=><HomeCard key={home.id} home={home}/>)}</div>:<div className="mt-9 rounded-[2rem] border border-white/10 bg-white/[.035] p-8 sm:p-10"><Building2 className="text-[#b8ff5a]" size={30}/><h3 className="mt-5 text-2xl font-black">Nog geen woningen geplaatst</h3><p className="mt-3 max-w-2xl leading-7 text-white/48">ASORTA begint bewust leeg. Zodra een echte huurder een woning plaatst en de activering afrondt, verschijnt die hier.</p><Link href="/place-home" className="btn-primary mt-6">Plaats de eerste woning</Link></div>}</section>
  <section className="mx-auto max-w-7xl px-4 pb-12 sm:px-5"><div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.035]"><div className="grid gap-px bg-white/10 md:grid-cols-3">{[['01','Plaatsen','Voeg je woning, corporatie en woonwensen toe.'],['02','Matchen','Asorta controleert automatisch of jullie over en weer passen.'],['03','Ruilen','Chat veilig en start samen het officiële ruilproces.']].map(([n,title,text])=><div key={n} className="bg-[#080c11] p-7 sm:p-9"><span className="text-sm font-black text-[#b8ff5a]">{n}</span><h3 className="mt-8 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/48">{text}</p></div>)}</div><div className="flex flex-col items-start justify-between gap-5 p-7 sm:flex-row sm:items-center sm:p-9"><div><h2 className="text-2xl font-black">Laagdrempelig beginnen</h2><p className="mt-2 text-white/48">€2 per nieuwe woningplaatsing · €5 volledige zoek- en matchtoegang voor één jaar · geen automatische verlenging.</p></div><Link href="/pricing" className="btn-secondary shrink-0">Bekijk tarieven</Link></div></div></section>
</main>}
