import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { removeListingPhoto, updateHousingListing } from '@/app/housing/actions'
import HousingProviderPicker, { type HousingProviderOption } from '@/components/HousingProviderPicker'
import { Camera, Home, ImagePlus, LockKeyhole, PencilLine, Trash2 } from 'lucide-react'

export const dynamic='force-dynamic'
export const metadata={title:'Mijn advertentie wijzigen'}

export default async function EditHome({searchParams}:{searchParams:Promise<{saved?:string;photos?:string;photo_removed?:string;error?:string}>}){
  const p=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser()
  if(!user)redirect('/login?next=/edit-home')
  const[{data:listing},{data:providers=[]}]=await Promise.all([
    s.from('listings').select('*').eq('user_id',user.id).in('status',['draft','pending_payment','active','paused','reserved']).maybeSingle(),
    s.from('housing_providers').select('id,name,provider_type,verified').eq('active',true).order('name'),
  ])
  if(!listing)redirect('/place-home')
  if(listing.status==='reserved')return <main className="mx-auto grid min-h-[70vh] max-w-2xl place-items-center px-4 py-16"><section className="card rounded-[2rem] p-8 text-center sm:p-10"><LockKeyhole className="mx-auto text-[#b8ff5a]" size={42}/><h1 className="mt-5 text-3xl font-black">Advertentie tijdelijk vergrendeld</h1><p className="mt-3 leading-7 text-white/50">Deze woning zit in een lopend ruilproces. Om te voorkomen dat afspraken onderweg veranderen, kun je de advertentie nu niet aanpassen.</p><Link href="/account" className="btn-primary mt-6">Terug naar Mijn Asorta</Link></section></main>

  const{data:photoRows=[]}=await s.from('listing_photos').select('id,storage_path,position,moderation_status,moderation_note').eq('listing_id',listing.id).order('position')
  const photos=[] as any[]
  for(const photo of photoRows||[]){const{data:signed}=await s.storage.from('listing-photos').createSignedUrl(photo.storage_path,60*20);photos.push({...photo,url:signed?.signedUrl||null})}
  const roomLeft=Math.max(0,8-photos.length)

  return <main className="mx-auto min-h-screen max-w-5xl px-4 py-12 sm:px-5"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="kicker">Mijn woning</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Wijzig mijn advertentie</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-white/52">Herstel fouten, werk je omschrijving bij en voeg nieuwe foto's toe. Voor wijzigingen betaal je niet opnieuw.</p></div><Link href="/account" className="btn-secondary shrink-0">Annuleren</Link></div>
    {p.saved&&<Notice good>Je advertentie is bijgewerkt.{p.photos&&' Nieuwe foto’s zijn naar ASORTA gestuurd voor controle.'}</Notice>}{p.photo_removed&&<Notice good>De foto is uit je advertentie verwijderd.</Notice>}{p.error&&<Notice>{p.error}</Notice>}

    <section className="card mt-8 rounded-[2rem] p-6 sm:p-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><Camera className="text-[#b8ff5a]"/><h2 className="text-2xl font-black">Huidige foto's</h2></div><p className="mt-2 text-sm leading-6 text-white/45">Goedgekeurde foto's zijn openbaar. Nieuwe foto's worden pas zichtbaar nadat ASORTA ze heeft gecontroleerd.</p></div><span className="status-pill">{photos.length}/8 foto's</span></div>
      {photos.length?<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{photos.map((photo:any,index:number)=><article key={photo.id} className="overflow-hidden rounded-2xl border border-white/10 bg-black/20"><div className="aspect-[16/10] bg-white/[.03]">{photo.url?<img src={photo.url} alt={`Woningfoto ${index+1}`} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-white/25"><Camera/></div>}</div><div className="p-4"><div className="flex items-center justify-between gap-2"><strong className="text-sm">Foto {index+1}</strong><PhotoStatus status={photo.moderation_status}/></div>{photo.moderation_status==='rejected'&&photo.moderation_note&&<p className="mt-2 text-xs leading-5 text-red-200/70">Reden: {photo.moderation_note}</p>}<details className="mt-3"><summary className="cursor-pointer text-xs font-bold text-white/38 hover:text-red-200">Foto verwijderen</summary><form action={removeListingPhoto} className="mt-3 rounded-xl border border-red-400/15 bg-red-500/[.05] p-3"><input type="hidden" name="photo_id" value={photo.id}/><p className="text-xs leading-5 text-white/45">Deze foto verdwijnt direct uit je advertentie.</p><button className="mt-3 inline-flex items-center gap-2 text-xs font-black text-red-200"><Trash2 size={14}/> Definitief verwijderen</button></form></details></div></article>)}</div>:<p className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-sm text-amber-100/70">Je advertentie heeft momenteel geen foto's. Voeg hieronder minimaal één duidelijke woningfoto toe.</p>}
    </section>

    <form action={updateHousingListing} className="mt-7 grid gap-7" encType="multipart/form-data"><input type="hidden" name="listing_id" value={listing.id}/>
      <Section icon={<Home/>} title="Woninggegevens"><div className="grid gap-4 sm:grid-cols-2"><Select name="property_type" label="Woningtype *" defaultValue={listing.property_type}><option value="apartment">Appartement</option><option value="house">Eengezinswoning</option><option value="maisonette">Maisonnette</option><option value="studio">Studio</option><option value="senior">Seniorenwoning</option><option value="other">Overig</option></Select><HousingProviderPicker providers={(providers||[]) as HousingProviderOption[]} initialProviderId={listing.housing_provider_id}/><Input name="monthly_rent" label="Kale huur per maand *" type="number" min="1" step="0.01" defaultValue={listing.monthly_rent}/><Input name="service_costs" label="Servicekosten per maand" type="number" min="0" step="0.01" defaultValue={listing.service_costs}/><Input name="living_area_m2" label="Woonoppervlak (m²)" type="number" min="10" max="1000" defaultValue={listing.living_area_m2??''}/><Input name="rooms" label="Aantal kamers *" type="number" min="1" max="30" defaultValue={listing.rooms}/><Input name="bedrooms" label="Aantal slaapkamers" type="number" min="0" max="20" defaultValue={listing.bedrooms??''}/><Input name="floor" label="Verdieping" type="number" defaultValue={listing.floor??''}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Check name="has_garden" label="Tuin" checked={listing.has_garden}/><Check name="has_balcony" label="Balkon" checked={listing.has_balcony}/><Check name="has_elevator" label="Lift" checked={listing.has_elevator}/><Check name="ground_floor" label="Begane grond" checked={listing.ground_floor}/><Check name="wheelchair_accessible" label="Rolstoeltoegankelijk" checked={listing.wheelchair_accessible}/></div><label className="label mt-4"><span>Toegankelijkheid of bijzonderheden</span><input name="accessibility" className="field" defaultValue={listing.accessibility||''} maxLength={500} placeholder="Bijv. gelijkvloers bereikbaar"/></label></Section>

      <Section icon={<LockKeyhole/>} title="Adres — blijft privé"><div className="grid gap-4 sm:grid-cols-2"><Input name="province" label="Provincie *" defaultValue={listing.province}/><Input name="municipality" label="Gemeente *" defaultValue={listing.municipality}/><Input name="city" label="Woonplaats *" defaultValue={listing.city}/><Input name="district" label="Wijk" defaultValue={listing.district||''}/><Input name="postcode4" label="Eerste 4 cijfers postcode *" inputMode="numeric" maxLength={4} defaultValue={listing.postcode4}/><Input name="street" label="Straat *" defaultValue={listing.street}/><Input name="house_number" label="Huisnummer + toevoeging *" defaultValue={listing.house_number}/><Input name="household_size" label="Huishoudgrootte" type="number" min="1" max="20" defaultValue={listing.household_size??''}/></div><label className="label mt-4"><span>Beschikbaar vanaf</span><input name="available_from" className="field" type="date" defaultValue={listing.available_from||''}/></label><p className="mt-4 text-sm leading-6 text-white/42">Je straat en huisnummer blijven afgeschermd. Publiek tonen we alleen de beperkte woninginformatie die nodig is om te zoeken en matchen.</p></Section>

      <Section icon={<PencilLine/>} title="Omschrijving en extra informatie"><label className="label"><span>Vertel iets over je woning *</span><textarea name="description" className="field min-h-48 resize-y" minLength={30} maxLength={3000} defaultValue={listing.description} required/></label><p className="mt-3 text-sm leading-6 text-white/42">Beschrijf bijvoorbeeld de indeling, buurt, buitenruimte, bergruimte, bereikbaarheid en wat je woning prettig maakt. Zet hier geen telefoonnummer, e-mailadres of exact adres in.</p></Section>

      <Section icon={<ImagePlus/>} title="Extra foto's toevoegen"><label className="label"><span>Nieuwe woningfoto's {roomLeft?`(nog maximaal ${roomLeft})`:'(maximum bereikt)'}</span><input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={!roomLeft} className="field file:mr-4 file:rounded-full file:border-0 file:bg-[#b8ff5a] file:px-4 file:py-2 file:font-black file:text-black disabled:opacity-40"/><small className="text-white/38">JPG, PNG of WebP, maximaal 10 MB per foto. Nieuwe foto's krijgen eerst de status ‘In controle’.</small></label>{!roomLeft&&<p className="mt-3 text-sm text-amber-100/65">Verwijder eerst een bestaande foto als je een andere wilt toevoegen.</p>}</Section>

      <div className="flex flex-col items-start justify-between gap-4 rounded-[2rem] border border-[#b8ff5a]/20 bg-[#b8ff5a]/[.06] p-6 sm:flex-row sm:items-center"><div><strong className="text-xl">Wijzigen is gratis</strong><p className="mt-1 text-sm text-white/48">Je bestaande activering blijft behouden; er volgt geen nieuwe betaling.</p></div><button className="btn-primary shrink-0 gap-2"><PencilLine size={17}/> Wijzigingen opslaan</button></div>
    </form>
  </main>
}

function Section({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="card rounded-[2rem] p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#b8ff5a] text-black [&_svg]:h-5 [&_svg]:w-5">{icon}</span><h2 className="text-2xl font-black">{title}</h2></div>{children}</section>}
function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="label"><span>{label}</span><input {...props} className="field" required={label.includes('*')||props.required}/></label>}
function Select({label,children,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <label className="label"><span>{label}</span><select {...props} className="field" required={label.includes('*')||props.required}>{children}</select></label>}
function Check({name,label,checked}:{name:string;label:string;checked?:boolean}){return <label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/10 bg-black/15 p-4 text-sm font-bold"><input name={name} type="checkbox" defaultChecked={Boolean(checked)} className="accent-[#b8ff5a]"/>{label}</label>}
function PhotoStatus({status}:{status:string}){const styles=status==='approved'?'bg-[#b8ff5a]/10 text-[#dcffb5]':status==='rejected'?'bg-red-500/10 text-red-200':'bg-amber-300/10 text-amber-100',label=status==='approved'?'Goedgekeurd':status==='rejected'?'Afgekeurd':'In controle';return <span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${styles}`}>{label}</span>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm font-bold ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10 text-[#dcffb5]':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
