export type Product = {
  slug:string; name:string; category:string; price:number; compareAt?:number; cost:number; hero:string; badge:string; short:string; description:string; features:string[]; specs:string[]; contentIdeas:string[]; supplierNotes:string; marginNote:string;
}
export const categories = [
  {slug:'tactical', name:'Tactical', text:'EDC gear, bags and utility essentials.'},
  {slug:'automotive', name:'Automotive', text:'Premium upgrades for your car interior.'},
  {slug:'desk-setup', name:'Desk Setup', text:'Clean organization and daily productivity gear.'},
  {slug:'gaming', name:'Gaming', text:'Setup accessories with premium utility.'},
  {slug:'smart-utility', name:'Smart Utility', text:'Useful tech gadgets for daily life.'},
  {slug:'outdoor', name:'Outdoor', text:'Camping and recovery utility products.'},
]
export const products: Product[] = [
{slug:'tactical-sling-bag-pro',name:'ASORTA Tactical Sling Bag Pro',category:'tactical',price:69.95,compareAt:89.95,cost:24,hero:'/products/tactical-sling-bag-pro.svg',badge:'Launch Pick',short:'Compact everyday carry bag with tactical organization.',description:'Built for daily carry, travel and urban utility. Multiple compartments keep tools, wallet, keys, powerbank and tech accessories locked in place without bulky backpack vibes.',features:['Water-resistant tactical fabric','Fast-access front compartment','Crossbody comfort strap','Hidden anti-theft pocket'],specs:['Capacity: 6-8L','Material: nylon/poly blend','Use: EDC, travel, work','Positioning: premium utility'],contentIdeas:['EDC loadout video','Before/after pocket dump','Travel day carry setup'],supplierNotes:'Source from EU/US warehouse where possible. Demand real product photos and zipper quality check.',marginNote:'Healthy target margin at €69.95 if landed cost stays below €30.'},
{slug:'edc-flashlight-titan',name:'EDC Flashlight Titan',category:'tactical',price:39.95,compareAt:54.95,cost:11,hero:'/products/edc-flashlight-titan.svg',badge:'EDC Essential',short:'Pocket-size flashlight with strong utility and premium feel.',description:'A compact tactical-style flashlight for car, desk, camping and everyday carry. High perceived value, easy to demonstrate, low return risk when sourced well.',features:['Compact metal body','Multiple light modes','Pocket clip','Emergency-ready utility'],specs:['Use: EDC/outdoor/car','Material: aluminium alloy','Battery: rechargeable preferred','Content fit: strong'],contentIdeas:['Dark room beam test','Car emergency kit clip','Camping utility reel'],supplierNotes:'Avoid suppliers with weak battery reviews. Prefer USB-C rechargeable versions.',marginNote:'Good low-ticket product for bundles and cart add-ons.'},
{slug:'minimalist-rfid-wallet',name:'Minimalist RFID Wallet',category:'tactical',price:44.95,compareAt:59.95,cost:10,hero:'/products/minimalist-rfid-wallet.svg',badge:'Best Seller Candidate',short:'Slim metal wallet for clean daily carry.',description:'A sleek wallet that fits the ASORTA identity perfectly: minimal, tactical, useful and premium. Great as evergreen product with strong gifting potential.',features:['RFID blocking','Slim metal design','Quick card access','Premium pocket carry'],specs:['Cards: 6-10','Material: aluminium/carbon style','Use: daily carry','Upsell: key organizer'],contentIdeas:['Bulky wallet vs ASORTA wallet','Pocket fit demo','Gift unboxing clip'],supplierNotes:'Competition is high, so only use premium-looking variants with strong reviews.',marginNote:'High perceived value; price must stay premium but believable.'},
{slug:'tactical-carabiner-tool',name:'Tactical Carabiner Multi-Tool',category:'tactical',price:24.95,compareAt:34.95,cost:5,hero:'/products/tactical-carabiner-tool.svg',badge:'Add-on',short:'Small utility tool for keys, bags and outdoor use.',description:'A compact add-on product that increases average order value. Works best as bundle product with bags, wallets and outdoor gear.',features:['Multi-use utility','Keychain compatible','Lightweight metal body','Great bundle item'],specs:['Use: EDC/outdoor','Margin: strong','Refund risk: low','Bundle fit: excellent'],contentIdeas:['Everyday keychain setup','5 uses in 15 seconds','Bag accessory closeup'],supplierNotes:'Check local regulations and avoid blade/weapon versions.',marginNote:'Excellent add-on margin when bundled.'},
{slug:'premium-car-ambient-kit',name:'Premium Car Ambient Light Kit',category:'automotive',price:79.95,compareAt:109.95,cost:25,hero:'/products/premium-car-ambient-kit.svg',badge:'Hero Product',short:'Transform your car interior with clean ambient lighting.',description:'One of the strongest visual products for social content. Creates instant before/after impact and fits the luxury utility identity when presented cleanly.',features:['Cinematic interior upgrade','App or remote control variants','Multiple lighting modes','Strong visual transformation'],specs:['Use: car interior','Content potential: very high','Installation: clear guide needed','Refund risk: medium if instructions are poor'],contentIdeas:['Before/after night interior','Luxury car vibe transformation','Install timelapse'],supplierNotes:'Only choose kits with strong installation reviews, clear manuals and stable LEDs.',marginNote:'Strong margin possible, but include clear installation expectations.'},
{slug:'magsafe-car-mount-pro',name:'Magnetic Car Mount Pro',category:'automotive',price:34.95,compareAt:49.95,cost:8,hero:'/products/magsafe-car-mount-pro.svg',badge:'Daily Utility',short:'Clean magnetic phone mount for modern dashboards.',description:'A simple, useful and low-refund car accessory. Strong fit for customers who want a clean cockpit without bulky holders.',features:['Strong magnetic hold','Minimal dashboard look','One-hand placement','Universal daily use'],specs:['Use: automotive','Install: adhesive/vent variant','Upsell: charging cable','Refund risk: low'],contentIdeas:['One-hand snap demo','Clean dashboard setup','Bumpy road hold test'],supplierNotes:'Test magnet strength before scaling. Avoid weak adhesive versions.',marginNote:'Strong margin and easy add-on to car collection.'},
{slug:'luxury-trunk-organizer',name:'Luxury Trunk Organizer',category:'automotive',price:59.95,compareAt:79.95,cost:20,hero:'/products/luxury-trunk-organizer.svg',badge:'Practical Pick',short:'Premium organization for groceries, tools and family trips.',description:'Practical, useful and easy to understand. Perfect for people who want their car clean and organized without cheap plastic storage boxes.',features:['Foldable structure','Multiple compartments','Clean premium look','Great for family and travel'],specs:['Use: car storage','Size: supplier dependent','Buyer type: practical','Refund risk: low'],contentIdeas:['Messy trunk transformation','Family trip packing','Tools and emergency kit setup'],supplierNotes:'Prefer sturdy versions with non-slip base and reinforced handles.',marginNote:'Good AOV product with low refund risk.'},
{slug:'wireless-charging-car-dock',name:'Wireless Charging Car Dock',category:'automotive',price:49.95,compareAt:69.95,cost:16,hero:'/products/wireless-charging-car-dock.svg',badge:'Smart Car',short:'Mount and charge your phone in one clean motion.',description:'Combines daily utility with tech convenience. Works well as premium car accessory when positioned as cockpit upgrade.',features:['Wireless charging','Secure phone hold','Clean interior look','Daily commute utility'],specs:['Use: car tech','Connection: USB-C preferred','Compatibility: list clearly','Refund risk: medium'],contentIdeas:['Drop-and-charge demo','Commute setup reel','Cable-free dashboard clip'],supplierNotes:'Check charging speed, phone compatibility and heat complaints.',marginNote:'Good margin but needs honest specs to avoid refunds.'},
{slug:'monitor-lightbar-ultra',name:'Monitor Lightbar Ultra',category:'desk-setup',price:64.95,compareAt:84.95,cost:22,hero:'/products/monitor-lightbar-ultra.svg',badge:'Desk Hero',short:'Clean desk lighting without screen glare.',description:'A highly visual desk upgrade for work, gaming and content setups. Strong evergreen product with premium appeal.',features:['Glare-reduced desk lighting','Minimal monitor mount','Warm/cool light modes','Clean setup aesthetic'],specs:['Use: desk/gaming','Power: USB preferred','Content potential: high','Refund risk: low-medium'],contentIdeas:['Desk setup transformation','Night productivity reel','Cable-free clean setup'],supplierNotes:'Prioritize versions with good mounting stability and brightness control.',marginNote:'Strong perceived value around €60-70.'},
{slug:'premium-desk-mat',name:'ASORTA Premium Desk Mat',category:'desk-setup',price:39.95,compareAt:54.95,cost:12,hero:'/products/premium-desk-mat.svg',badge:'Setup Essential',short:'Large clean desk mat for work and gaming setups.',description:'Simple evergreen product that improves setup visuals. Strong for bundles with cable management, lightbar and docks.',features:['Large workspace surface','Smooth mouse movement','Minimal premium look','Protects desk surface'],specs:['Use: desk/gaming','Material: PU/fabric variants','Bundle fit: excellent','Refund risk: low'],contentIdeas:['Messy desk to clean desk','Keyboard/mouse glide demo','Premium setup flatlay'],supplierNotes:'Private label potential later. Start with neutral premium designs.',marginNote:'Good bundle product; margins improve with own branding.'},
{slug:'cable-management-kit',name:'Cable Management Kit',category:'desk-setup',price:29.95,compareAt:39.95,cost:7,hero:'/products/cable-management-kit.svg',badge:'Low Refund',short:'Clean up your desk cables with a complete utility kit.',description:'A practical product that solves a real problem. Best sold with setup transformation content and desk bundles.',features:['Clips, sleeves and ties','Cleaner setup instantly','Easy installation','Perfect bundle item'],specs:['Use: desk/office/gaming','Complexity: low','Refund risk: low','AOV role: add-on'],contentIdeas:['Cable chaos before/after','Under-desk cleanup timelapse','Home office upgrade'],supplierNotes:'Choose kits with enough components and clear product images.',marginNote:'Strong add-on margin and low support burden.'},
{slug:'charging-station-3in1',name:'3-in-1 Charging Station',category:'desk-setup',price:54.95,compareAt:74.95,cost:18,hero:'/products/charging-station-3in1.svg',badge:'Smart Desk',short:'Charge phone, earbuds and watch from one clean dock.',description:'A strong daily utility product for modern setups. Works especially well for Apple-style customers when compatibility is made clear.',features:['Multi-device charging','Minimal desk footprint','Clean nightstand or desk look','Daily convenience'],specs:['Use: desk/nightstand','Compatibility: state clearly','Power: supplier dependent','Refund risk: medium'],contentIdeas:['Nightstand setup','Desk charging transformation','One cable setup'],supplierNotes:'Compatibility clarity is critical. Avoid overheating complaints.',marginNote:'Good margin if quality is high and specs are honest.'},
{slug:'rgb-headset-stand',name:'RGB Headset Stand Dock',category:'gaming',price:39.95,compareAt:54.95,cost:12,hero:'/products/rgb-headset-stand.svg',badge:'Gaming Setup',short:'Premium headset stand with clean setup presence.',description:'A visual gaming product that adds organization and setup lighting. Good starter product for gaming category.',features:['Headset storage','RGB setup accent','Stable desk base','Clean gaming aesthetic'],specs:['Use: gaming desk','Power: USB','Buyer type: setup lovers','Refund risk: low'],contentIdeas:['Gaming setup glow-up','Desk organization reel','RGB night shot'],supplierNotes:'Look for stable base and clean RGB implementation.',marginNote:'Good perceived value when positioned as setup upgrade.'},
{slug:'controller-charging-dock',name:'Controller Charging Dock',category:'gaming',price:34.95,compareAt:44.95,cost:10,hero:'/products/controller-charging-dock.svg',badge:'Console Utility',short:'Keep controllers charged and displayed cleanly.',description:'Useful for console gamers and easy to understand. Strong product if variants are split clearly by console type.',features:['Dual controller charging','Clean display stand','LED charge indicators','Setup organization'],specs:['Use: console gaming','Compatibility: PS/Xbox variants','Refund risk: medium if unclear','Bundle: gaming'],contentIdeas:['Dead controller problem solved','Console setup organization','Charging indicator demo'],supplierNotes:'Create separate product variants for PS/Xbox to prevent wrong orders.',marginNote:'Good margin; reduce refunds with clear variant selection.'},
{slug:'gaming-light-panels',name:'Modular Gaming Light Panels',category:'gaming',price:89.95,compareAt:119.95,cost:35,hero:'/products/gaming-light-panels.svg',badge:'Visual Hero',short:'Cinematic wall lighting for gaming and streaming setups.',description:'High visual impact product with strong content potential. Needs good quality sourcing because cheap panels can create support issues.',features:['Modular wall design','Multiple lighting modes','Strong room transformation','Streamer-ready aesthetic'],specs:['Use: gaming/streaming','Content potential: very high','Install: adhesive/mounting','Refund risk: medium'],contentIdeas:['Room transformation','Streamer wall setup','Before/after lighting reel'],supplierNotes:'Only use suppliers with stable app/control reviews and real buyer images.',marginNote:'Higher ticket product; margin must cover support risk.'},
{slug:'smart-key-finder',name:'Smart Key Finder',category:'smart-utility',price:29.95,compareAt:39.95,cost:8,hero:'/products/smart-key-finder.svg',badge:'Everyday Use',short:'Find keys, bags and essentials faster.',description:'Simple daily problem solver. Works well as low-ticket product and bundle add-on for bags, wallets and travel accessories.',features:['Attach to keys or bag','App-based finding','Compact design','Daily peace of mind'],specs:['Use: daily utility','Compatibility: specify clearly','Refund risk: medium','Bundle: EDC/travel'],contentIdeas:['Lost keys problem','Bag tracker demo','Family travel setup'],supplierNotes:'Avoid vague GPS claims. Be honest if it is Bluetooth-based.',marginNote:'Good add-on if expectations are clear.'},
{slug:'portable-mini-compressor',name:'Portable Mini Air Compressor',category:'smart-utility',price:69.95,compareAt:94.95,cost:27,hero:'/products/portable-mini-compressor.svg',badge:'Utility Hero',short:'Compact air pump for car, bike and emergency use.',description:'Very useful and easy to sell through problem-solution content. Strong fit for automotive and smart utility crossover.',features:['Portable inflation','Digital pressure display preferred','Car and bike compatible','Emergency kit essential'],specs:['Use: car/bike/outdoor','Power: rechargeable preferred','Refund risk: medium','Content potential: high'],contentIdeas:['Flat tire emergency demo','Bike pump comparison','Car emergency kit reel'],supplierNotes:'Quality matters. Check accuracy, battery and overheating reviews.',marginNote:'Good perceived value and practical buyer intent.'},
{slug:'foldable-solar-powerbank',name:'Foldable Solar Powerbank',category:'outdoor',price:59.95,compareAt:79.95,cost:22,hero:'/products/foldable-solar-powerbank.svg',badge:'Outdoor Utility',short:'Backup power for camping, travel and emergency kits.',description:'Outdoor-friendly product with broad appeal. Must be marketed honestly: solar is backup charging, not magic fast charging.',features:['Portable backup power','Outdoor emergency use','Foldable solar panel style','Great camping companion'],specs:['Use: camping/travel','Capacity: supplier dependent','Refund risk: medium','Honest copy: required'],contentIdeas:['Camping power setup','Emergency bag loadout','Weekend trip utility'],supplierNotes:'Avoid exaggerated capacity claims. Verify real mAh and reviews.',marginNote:'Good margin if quality and claims are controlled.'},
{slug:'heated-neck-massager',name:'Heated Neck Recovery Massager',category:'smart-utility',price:49.95,compareAt:69.95,cost:17,hero:'/products/heated-neck-massager.svg',badge:'Recovery',short:'Daily relaxation and recovery for desk workers and drivers.',description:'Useful recovery product with strong buyer intent. Needs careful claims: position as comfort and relaxation, not medical treatment.',features:['Heat comfort mode','Portable relaxation','Desk worker friendly','Driver recovery use'],specs:['Use: relaxation','Claims: no medical promises','Refund risk: medium','Audience: office/drivers'],contentIdeas:['After work recovery routine','Desk neck tension comfort','Driver rest setup'],supplierNotes:'Check safety certifications and avoid medical claims.',marginNote:'Good margin but support quality must be monitored.'},
{slug:'premium-pet-hair-detailer',name:'Premium Pet Hair Detailer',category:'automotive',price:24.95,compareAt:34.95,cost:5,hero:'/products/premium-pet-hair-detailer.svg',badge:'Viral Demo',short:'Remove pet hair from car seats, mats and fabric surfaces.',description:'A satisfying demo product that fits automotive and pet utility. Strong for short-form video because results are instantly visible.',features:['Removes embedded pet hair','Works on fabric surfaces','Reusable tool','Satisfying before/after'],specs:['Use: car/home fabric','Refund risk: low','Content potential: high','Bundle: car cleaning'],contentIdeas:['Car seat pet hair removal','Before/after closeup','Dog owner car cleanup'],supplierNotes:'Avoid versions that damage delicate fabrics; test or show warnings.',marginNote:'Excellent low-ticket viral add-on.'}
]
export const featured = products.filter(p=>['premium-car-ambient-kit','tactical-sling-bag-pro','monitor-lightbar-ultra','portable-mini-compressor'].includes(p.slug))
export function getProduct(slug:string){return products.find(p=>p.slug===slug)}
export function getCategory(slug:string){return categories.find(c=>c.slug===slug)}
export function byCategory(slug:string){return products.filter(p=>p.category===slug)}
