import Link from 'next/link'
import { Image as ImageIcon } from 'lucide-react'
import { assertAtlasPermission } from '@/lib/atlas-auth'
import { setListingStatus } from './actions'
import { moderatePhoto } from '../operations/actions'

export const dynamic='force-dynamic'
export const metadata={title:'Woningen | Atlas',robots:{index:false,follow:false}}

export default async function HousingAdmin({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
  const p=await searchParams,{admin}=await assertAtlasPermission('housing','/atlas/housing')
  const[{data:listings=[]},{data:matches=[]},{data:payments=[]},{data:reports=[]},{data:photos=[]}]=await Promise.all([
    admin.from('listings').select('id,status,city,property_type,monthly_rent,user_id,blocked_at,created_at,housing_providers(name)').order('created_at',{ascending:false}).limit(100),
    admin.from('matches').select('id,status,score,created_at').order('created_at',{ascending:false}).limit(30),
    admin.from('payments').select('id,purpose,amount,status,created_at').order('created_at',{ascending:false}).limit(30),
    admin.from('reports').select('id,reason,status,created_at').order('created_at',{ascending:false}).limit(30),
    admin.from('listing_photos').select('id,listing_id,storage_path,position,moderation_status,moderation_note,created_at').order('created_at',{ascending:false}).limit(40),
  ])
  const listingMap=new Map((listings||[]).map((x:any)=>[x.id,x])),photoCards=[] as any[]
  for(const photo of photos||[]){const{data:signed}=await admin.storage.from('listing-photos').createSignedUrl(photo.storage_path,60*20);photoCards.push({...photo,url:signed?.signedUrl||null,listing:listingMap.get(photo.listing_id)})}
  return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-5"><div className="flex items-end justify-between"><div><p className="kicker">Atlas beheer</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Woningen & platform</h1></div><Link href="/atlas" className="btn-secondary">Terug</Link></div>{p.saved&&<Notice good>Wijziging opgeslagen.</Notice>}{p.error&&<Notice>{p.error}</Notice>}
    <h2 className="mt-10 text-2xl font-black">Recente woningen</h2><div className="mt-4 overflow-x-auto rounded-[1.7rem] border border-white/10"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white/[.05] text-xs uppercase tracking-wider text-white/45"><tr><th className="p-4">Woning</th><th className="p-4">Corporatie</th><th className="p-4">Huur</th><th className="p-4">Status</th><th className="p-4">Actie</th></tr></thead><tbody>{(listings||[]).map((x:any)=><tr key={x.id} className="border-t border-white/10"><td className="p-4"><strong>{x.city}</strong><br/><span className="text-xs text-white/38">{x.property_type} · {x.id.slice(0,8)}</span></td><td className="p-4">{x.housing_providers?.name}</td><td className="p-4">€ {Number(x.monthly_rent).toFixed(2).replace('.',',')}</td><td className="p-4 uppercase">{x.blocked_at?'geblokkeerd':x.status}</td><td className="p-4"><form action={setListingStatus} className="flex gap-2"><input type="hidden" name="id" value={x.id}/><select name="status" defaultValue={x.status} className="field max-w-44 py-2"><option value="active">Actief</option><option value="paused">Gepauzeerd</option><option value="rejected">Afgekeurd</option><option value="removed">Verwijderd</option></select><button className="btn-secondary px-4 py-2">Opslaan</button></form></td></tr>)}</tbody></table>{!listings?.length&&<p className="p-8 text-center text-white/42">Nog geen echte woningen geplaatst.</p>}</div>
    <section className="mt-10"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Fotomoderatie</h2><span className="text-sm text-white/38">Nieuwe foto’s zijn pas openbaar na goedkeuring</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{photoCards.map((x:any)=><article key={x.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]"><div className="aspect-[16/10] bg-black/30">{x.url?<img src={x.url} alt="Te beoordelen woningfoto" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-white/20"><ImageIcon/></div>}</div><div className="p-4"><div className="flex items-center justify-between gap-2"><strong>{x.listing?.city||x.listing_id.slice(0,8)}</strong><span className="text-xs uppercase text-white/40">{x.moderation_status}</span></div><form action={moderatePhoto} className="mt-3 grid gap-2"><input type="hidden" name="photo_id" value={x.id}/><input name="note" defaultValue={x.moderation_note||''} className="field py-2 text-xs" placeholder="Reden bij afwijzing"/><div className="grid grid-cols-2 gap-2"><button name="status" value="rejected" className="btn-secondary px-3 py-2 text-xs text-red-100">Afwijzen</button><button name="status" value="approved" className="btn-primary px-3 py-2 text-xs">Goedkeuren</button></div></form></div></article>)}{!photoCards.length&&<div className="card rounded-2xl p-8 text-center text-white/42 sm:col-span-2 lg:col-span-3">Nog geen foto’s om te beoordelen.</div>}</div></section>
    <div className="mt-10 grid gap-5 lg:grid-cols-3"><Mini title="Matches" items={matches||[]} render={(x:any)=>`${x.score}% · ${x.status}`}/><Mini title="Betalingen" items={payments||[]} render={(x:any)=>`€${Number(x.amount).toFixed(2)} · ${x.purpose} · ${x.status}`}/><Mini title="Rapportages" items={reports||[]} render={(x:any)=>`${x.reason} · ${x.status}`}/></div>
  </main>
}
function Mini({title,items,render}:{title:string;items:any[];render:(x:any)=>string}){return <section className="card rounded-[1.7rem] p-5"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 grid gap-2">{items.slice(0,8).map(x=><div key={x.id} className="rounded-xl border border-white/8 bg-black/20 p-3 text-xs"><strong>{render(x)}</strong><time className="mt-1 block text-white/32">{new Date(x.created_at).toLocaleString('nl-NL')}</time></div>)}{!items.length&&<p className="text-sm text-white/38">Nog geen gegevens.</p>}</div></section>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm font-bold ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
