import Link from 'next/link'
import { Ban, Flag, ShieldCheck } from 'lucide-react'
import { assertAtlasPermission, hasAtlasPermission } from '@/lib/atlas-auth'
import { setReportStatus, setUserBlock } from '../operations/actions'

export const dynamic='force-dynamic'
export const metadata={title:'Rapportages | Atlas',robots:{index:false,follow:false}}

export default async function ReportsPage({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
  const p=await searchParams,{admin,staff}=await assertAtlasPermission('support','/atlas/reports'),canBlock=hasAtlasPermission(staff,'settings')
  const{data:reports=[]}=await admin.from('reports').select('*').order('created_at',{ascending:false}).limit(200)
  const ids=[...new Set((reports||[]).flatMap((x:any)=>[x.reporter_id,x.reported_user_id]).filter(Boolean))]
  const{data:profiles=[]}=ids.length?await admin.from('profiles').select('id,system_username,custom_display_name,display_name_mode,blocked_at,block_reason').in('id',ids):{data:[]}
  const profileMap=new Map((profiles||[]).map((x:any)=>[x.id,x]))
  return <main className="mx-auto max-w-6xl px-4 py-12 sm:px-5"><Header/><Notices p={p}/><div className="mt-8 grid gap-5">{(reports||[]).map((x:any)=>{const reported=profileMap.get(x.reported_user_id),name=reported?display(reported):'Onbekende gebruiker';return <article key={x.id} className="card rounded-[1.7rem] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><span className="status-pill">{x.status}</span><span className="text-xs text-white/35">{date(x.created_at)}</span></div><h2 className="mt-4 text-xl font-black">{x.reason}</h2><p className="mt-2 max-w-3xl whitespace-pre-wrap text-sm leading-6 text-white/52">{x.details||'Geen aanvullende toelichting.'}</p><p className="mt-3 text-xs text-white/35">Gemeld door {display(profileMap.get(x.reporter_id))} · Over {name}</p></div><form action={setReportStatus} className="flex items-end gap-2"><input type="hidden" name="id" value={x.id}/><select name="status" defaultValue={x.status} className="field min-w-36 py-2"><option value="open">Open</option><option value="reviewing">In onderzoek</option><option value="resolved">Opgelost</option><option value="dismissed">Afgewezen</option></select><button className="btn-secondary px-4 py-2">Opslaan</button></form></div>{reported&&canBlock&&<div className="mt-5 border-t border-white/10 pt-5">{reported.blocked_at?<form action={setUserBlock} className="flex flex-wrap items-center gap-3"><input type="hidden" name="user_id" value={reported.id}/><input type="hidden" name="blocked" value="false"/><span className="mr-auto text-sm text-red-200"><Ban className="mr-2 inline" size={16}/>{name} is geblokkeerd: {reported.block_reason||'geen reden opgeslagen'}</span><button className="btn-secondary">Deblokkeren</button></form>:<form action={setUserBlock} className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input type="hidden" name="user_id" value={reported.id}/><input type="hidden" name="blocked" value="true"/><input name="reason" className="field" placeholder="Reden voor blokkade"/><input name="confirmation" className="field" placeholder="Typ BLOKKEREN"/><button className="btn-secondary gap-2 text-red-100"><Ban size={16}/> Blokkeer account</button></form>}</div>}</article>})}{!reports?.length&&<div className="card rounded-[1.7rem] p-10 text-center"><ShieldCheck className="mx-auto text-[#b8ff5a]"/><h2 className="mt-4 text-2xl font-black">Geen openstaande rapportages</h2><p className="mt-2 text-white/42">Nieuwe gebruikersmeldingen verschijnen hier.</p></div>}</div></main>
}
function Header(){return <div className="flex items-end justify-between"><div><p className="kicker">Veiligheid</p><h1 className="mt-3 flex items-center gap-3 text-4xl font-black sm:text-6xl"><Flag className="text-[#b8ff5a]"/> Rapportages</h1></div><Link href="/atlas" className="btn-secondary">Terug</Link></div>}
function Notices({p}:{p:{saved?:string;error?:string}}){return <>{p.saved&&<div className="mt-6 rounded-2xl border border-[#b8ff5a]/25 bg-[#b8ff5a]/10 p-4 text-sm font-bold">Beheeractie opgeslagen.</div>}{p.error&&<div className="mt-6 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-sm text-red-100">{p.error}</div>}</>}
function display(x:any){if(!x)return 'Onbekende ruiler';return x.display_name_mode==='custom'&&x.custom_display_name?x.custom_display_name:x.system_username}
function date(v:string){return new Date(v).toLocaleString('nl-NL')}
