import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { blockMatchUser, cancelSwap, confirmSwapCompletion, decideMatch, reportMatchUser, sendMatchMessage, updateProviderProgress } from '@/app/housing/actions'
import { Building2, Check, Circle, Home, MapPin, MessageCircle, ShieldCheck, X } from 'lucide-react'

export const dynamic='force-dynamic'
export default async function MatchDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;decision?:string;completed?:string;reported?:string}>}){
  const {id}=await params,p=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser()
  if(!user)redirect(`/login?next=/matches/${id}`)
  const {data:match}=await s.from('matches').select('*').eq('id',id).maybeSingle()
  if(!match)notFound()
  const otherId=match.user_a_id===user.id?match.user_b_id:match.user_a_id
  const [{data:homes=[]},{data:names=[]},{data:decisions=[]},{data:conversation},{data:swap}]=await Promise.all([
    s.from('match_listings').select('*').eq('match_id',id),
    s.from('public_profiles').select('*').in('id',[user.id,otherId]),
    s.from('match_decisions').select('*').eq('match_id',id),
    s.from('conversations').select('*').eq('match_id',id).maybeSingle(),
    s.from('swap_cases').select('*,provider_a:housing_providers!swap_cases_provider_a_id_fkey(*),provider_b:housing_providers!swap_cases_provider_b_id_fkey(*)').eq('match_id',id).maybeSingle(),
  ])
  const [{data:messages=[]},{data:providerProgress=[]}]=await Promise.all([
    conversation?s.from('messages').select('*').eq('conversation_id',conversation.id).order('created_at') : Promise.resolve({data:[]}),
    swap?s.from('swap_provider_status').select('*').eq('swap_case_id',swap.id):Promise.resolve({data:[]}),
  ])
  const nameMap=new Map((names||[]).map((n:any)=>[n.id,n.display_name])),mine=(homes||[]).find((h:any)=>h.user_id===user.id),other=(homes||[]).find((h:any)=>h.user_id===otherId),myDecision=(decisions||[]).find((d:any)=>d.user_id===user.id)?.decision||'pending',otherDecision=(decisions||[]).find((d:any)=>d.user_id===otherId)?.decision||'pending'
  return <main className="mx-auto min-h-screen max-w-6xl px-4 py-10 sm:px-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="kicker">Wederzijdse match · {match.score}%</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Jij ↔ {nameMap.get(otherId)||'Ruiler'}</h1></div><span className="status-pill">{statusLabel(match.status)}</span></div>{p.error&&<Notice>{p.error}</Notice>}{p.completed&&<Notice good>Jouw bevestiging is opgeslagen. Als de ander ook bevestigt, wisselt Asorta de woninggegevens veilig om.</Notice>}{p.reported&&<Notice good>Je melding is veilig ontvangen door ASORTA.</Notice>}
    <section className="mt-7 grid gap-4 md:grid-cols-2"><HomePanel title="Jouw woning" home={mine}/><HomePanel title={`Woning van ${nameMap.get(otherId)||'de andere ruiler'}`} home={other}/></section>
    {swap?<SwapPanel swap={swap} progress={providerProgress||[]} userId={user.id} matchId={id}/>:<DecisionPanel matchId={id} mine={myDecision} other={otherDecision}/>} 
    <section id="chat" className="mt-7 overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.035]"><div className="flex items-center gap-3 border-b border-white/10 p-5 sm:p-6"><MessageCircle className="text-[#b8ff5a]"/><div><h2 className="text-2xl font-black">Privéchat</h2><p className="mt-1 text-xs text-white/40">Je praat nu als {nameMap.get(user.id)||'Ruiler'}</p></div></div><div className="min-h-64 space-y-3 p-5 sm:p-6">{(messages||[]).length?(messages||[]).map((m:any)=><div key={m.id} className={`flex ${m.sender_id===user.id?'justify-end':'justify-start'}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.sender_id===user.id?'bg-[#b8ff5a] text-black':'border border-white/10 bg-black/25 text-white/72'}`}><strong className="mb-1 block text-xs opacity-60">{nameMap.get(m.sender_id)||'Ruiler'}</strong>{m.body}<time className="mt-1 block text-[11px] opacity-45">{new Date(m.created_at).toLocaleString('nl-NL')}</time></div></div>):<div className="grid min-h-52 place-items-center text-center"><div><MessageCircle className="mx-auto text-white/20"/><p className="mt-3 text-sm text-white/42">Begin rustig en stel vragen over de woning of buurt.<br/>Deel nog geen gevoelige gegevens.</p></div></div>}</div>{conversation&&conversation.status==='active'&&<form action={sendMatchMessage} className="flex gap-3 border-t border-white/10 p-4"><input type="hidden" name="match_id" value={id}/><input type="hidden" name="conversation_id" value={conversation.id}/><input name="body" className="field" placeholder="Schrijf een bericht..." maxLength={2000}/><button className="btn-primary shrink-0">Verstuur</button></form>}</section><details className="mt-6 rounded-2xl border border-white/10 bg-white/[.025]"><summary className="cursor-pointer list-none p-5 text-sm font-black text-white/55">Melden of blokkeren</summary><div className="grid gap-5 border-t border-white/10 p-5 md:grid-cols-2"><form action={reportMatchUser} className="grid gap-3"><input type="hidden" name="match_id" value={id}/><strong>Stuur een melding naar ASORTA</strong><input name="reason" className="field" placeholder="Reden van de melding"/><textarea name="details" className="field min-h-24" placeholder="Wat is er gebeurd?"/><button className="btn-secondary justify-self-start">Melding versturen</button></form><form action={blockMatchUser} className="grid content-start gap-3"><input type="hidden" name="match_id" value={id}/><strong>Blokkeer deze gebruiker</strong><p className="text-sm leading-6 text-white/42">De chat en deze match worden gesloten. Jullie worden niet opnieuw aan elkaar gekoppeld.</p><input name="confirmation" className="field" placeholder="Typ BLOKKEREN"/><button className="btn-secondary justify-self-start text-red-100">Gebruiker blokkeren</button></form></div></details>
  </main>
}

function HomePanel({title,home}:{title:string;home:any}){return <article className="card rounded-[2rem] p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/7 text-[#b8ff5a]"><Home size={20}/></span><h2 className="font-black">{title}</h2></div>{home?<><strong className="mt-6 block text-2xl">{home.city}</strong><p className="mt-2 flex items-center gap-2 text-sm text-white/48"><MapPin size={15}/>{home.district||home.province} · {home.rooms} kamers · € {Number(home.monthly_rent).toFixed(0)} p/m</p><p className="mt-4 line-clamp-3 text-sm leading-6 text-white/45">{home.description}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-white/38"><Building2 size={14}/>{home.provider_name}</span></>:<p className="mt-6 text-sm text-white/42">Woninggegevens worden geladen.</p>}</article>}

function DecisionPanel({matchId,mine,other}:{matchId:string;mine:string;other:string}){return <section className="mt-7 rounded-[2rem] border border-white/10 bg-white/[.035] p-6 sm:p-8"><p className="kicker">Jullie keuze</p><h2 className="mt-3 text-3xl font-black">Willen jullie deze ruil onderzoeken?</h2><p className="mt-3 max-w-3xl leading-7 text-white/50">Pas na twee keer “Ja” pauzeren we beide woningen en start het ruildossier. Een “Nee” brengt iedereen direct terug in de matching.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><DecisionRow label="Jouw keuze" value={mine}/><DecisionRow label="Keuze andere ruiler" value={other}/></div>{mine==='pending'&&<div className="mt-6 flex flex-col gap-3 sm:flex-row"><form action={decideMatch}><input type="hidden" name="match_id" value={matchId}/><input type="hidden" name="decision" value="yes"/><button className="btn-primary w-full gap-2 sm:w-auto"><Check size={18}/> Ja, ik wil ruilen</button></form><form action={decideMatch}><input type="hidden" name="match_id" value={matchId}/><input type="hidden" name="decision" value="no"/><button className="btn-secondary w-full gap-2 sm:w-auto"><X size={18}/> Nee, toch niet</button></form></div>}{mine==='yes'&&other!=='yes'&&<p className="mt-6 rounded-2xl border border-[#b8ff5a]/20 bg-[#b8ff5a]/[.06] p-4 text-sm font-bold text-[#dcffb5]">Jij wilt verder. We wachten op de andere woningruiler.</p>}</section>}
function DecisionRow({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 p-4"><span className="text-xs font-bold text-white/38">{label}</span><strong className="mt-2 flex items-center gap-2">{value==='yes'?<Check className="text-[#b8ff5a]"/>:value==='no'?<X className="text-red-300"/>:<Circle className="text-white/25"/>}{value==='yes'?'Wil ruilen':value==='no'?'Wil niet ruilen':'Nog geen keuze'}</strong></div>}

function SwapPanel({swap,progress,userId,matchId}:{swap:any;progress:any[];userId:string;matchId:string}){const mine=progress.find(x=>x.user_id===userId),provider=swap.user_a_id===userId?swap.provider_a:swap.provider_b,otherProvider=swap.user_a_id===userId?swap.provider_b:swap.provider_a,canComplete=['approved','awaiting_decision'].includes(swap.status);return <section className="mt-7 rounded-[2rem] border border-[#b8ff5a]/20 bg-[#b8ff5a]/[.045] p-6 sm:p-8"><p className="kicker">Ruilproces gestart</p><h2 className="mt-3 text-3xl font-black">Jullie willen allebei verder</h2><p className="mt-3 max-w-3xl leading-7 text-white/52">Beide woningen zijn tijdelijk uit de matching gehaald. Vraag ieder afzonderlijk toestemming aan de eigen verhuurder; Asorta verleent zelf geen toestemming.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><Provider provider={provider} title="Jouw verhuurder"/><Provider provider={otherProvider} title="Verhuurder andere woning"/></div>{mine&&<form action={updateProviderProgress} className="mt-6 flex flex-col gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 sm:flex-row sm:items-end"><input type="hidden" name="match_id" value={matchId}/><input type="hidden" name="provider_status_id" value={mine.id}/><label className="label flex-1"><span>Voortgang bij jouw verhuurder</span><select name="status" defaultValue={mine.status} className="field"><option value="not_started">Nog niet gestart</option><option value="contacted">Contact opgenomen</option><option value="submitted">Aanvraag ingediend</option><option value="pending">In behandeling</option><option value="approved">Goedgekeurd</option><option value="rejected">Afgewezen</option></select></label><button className="btn-primary">Opslaan</button></form>}<div className="mt-6 flex flex-col gap-3 sm:flex-row">{canComplete&&<form action={confirmSwapCompletion}><input type="hidden" name="match_id" value={matchId}/><input type="hidden" name="swap_case_id" value={swap.id}/><button className="btn-primary gap-2"><Check size={18}/> De woningruil is voltooid</button></form>}<form action={cancelSwap}><input type="hidden" name="match_id" value={matchId}/><input type="hidden" name="swap_case_id" value={swap.id}/><button className="btn-secondary gap-2"><X size={18}/> Ruil toch annuleren</button></form></div><p className="mt-5 flex gap-2 text-xs leading-5 text-white/38"><ShieldCheck size={15} className="mt-0.5 shrink-0"/>De woninggegevens wisselen pas van gebruikersprofiel nadat beide huurders de voltooide ruil bevestigen.</p></section>}
function Provider({provider,title}:{provider:any;title:string}){return <div className="rounded-2xl border border-white/10 bg-black/20 p-5"><span className="text-xs font-bold text-white/38">{title}</span><h3 className="mt-2 text-xl font-black">{provider?.name||'Verhuurder'}</h3><div className="mt-4 grid gap-2 text-sm text-white/55">{provider?.swap_info_url&&<a href={provider.swap_info_url} target="_blank" rel="noreferrer" className="font-bold text-[#b8ff5a]">Informatie over woningruil ↗</a>}{provider?.swap_application_url&&<a href={provider.swap_application_url} target="_blank" rel="noreferrer" className="font-bold text-[#b8ff5a]">Aanvraagformulier ↗</a>}{provider?.contact_phone&&<span>{provider.contact_phone}</span>}{provider?.contact_email&&<span>{provider.contact_email}</span>}{!provider?.swap_info_url&&!provider?.contact_phone&&!provider?.contact_email&&<span>Contactgegevens worden door Asorta gecontroleerd.</span>}</div></div>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm font-bold ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10 text-[#dcffb5]':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
function statusLabel(status:string){return ({active:'Match in gesprek',swap_in_progress:'Ruil in behandeling',declined:'Afgewezen',temporarily_unavailable:'Tijdelijk gepauzeerd',cancelled:'Gestopt',completed:'Voltooid'} as Record<string,string>)[status]||status}
