import Link from 'next/link'
import { Building2, Plus, ShieldCheck } from 'lucide-react'
import { assertAtlasPermission } from '@/lib/atlas-auth'
import { updateProvider } from '../housing/actions'
import { createProvider, reviewProviderSuggestion } from '../operations/actions'

export const dynamic='force-dynamic'
export const metadata={title:'Corporaties | Atlas',robots:{index:false,follow:false}}

export default async function ProvidersAdmin({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
  const p=await searchParams,{admin}=await assertAtlasPermission('providers','/atlas/providers')
  const[{data:providerRows},{data:suggestionRows}]=await Promise.all([admin.from('housing_providers').select('*').order('name'),admin.from('housing_provider_suggestions').select('*').eq('status','pending').order('created_at',{ascending:false}).limit(100)]),providers=providerRows||[],suggestions=suggestionRows||[]
  return <main className="mx-auto max-w-6xl px-4 py-12 sm:px-5"><div className="flex items-end justify-between gap-4"><div><p className="kicker">Atlas beheer</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Corporaties</h1><p className="mt-3 text-white/45">Markeer een verhuurder alleen als geverifieerd na controle bij een officiële bron.</p></div><Link href="/atlas" className="btn-secondary">Terug</Link></div>{p.saved&&<Notice good>Corporatiebeheer bijgewerkt.</Notice>}{p.error&&<Notice>{p.error}</Notice>}
    <details className="card mt-8 rounded-[1.7rem]"><summary className="flex cursor-pointer list-none items-center gap-3 p-5 text-xl font-black"><Plus className="text-[#b8ff5a]"/> Nieuwe verhuurder toevoegen</summary><form action={createProvider} className="grid gap-4 border-t border-white/10 p-5 sm:grid-cols-2"><Input name="name" label="Naam *" required/><label className="label"><span>Type *</span><select name="provider_type" className="field" defaultValue="housing_corporation"><option value="housing_corporation">Woningcorporatie</option><option value="private_landlord">Particuliere verhuurder</option><option value="municipality">Gemeente</option><option value="other">Overig</option></select></label><Input name="website_url" label="Website"/><Input name="contact_email" label="E-mail" type="email"/><Input name="contact_phone" label="Telefoon"/><Input name="swap_info_url" label="Informatie woningruil"/><Input name="swap_application_url" label="Aanvraagformulier"/><Input name="source_url" label="Officiële bron"/><button className="btn-primary justify-self-start sm:col-span-2">Toevoegen als ongeverifieerd</button></form></details>
    {suggestions.length>0&&<section className="mt-8"><h2 className="text-2xl font-black">Ingediende voorstellen</h2><div className="mt-4 grid gap-3">{suggestions.map((x:any)=><div key={x.id} className="card flex flex-col gap-4 rounded-2xl p-5 md:flex-row md:items-center"><div className="mr-auto"><strong>{x.name}</strong><p className="mt-1 text-sm text-white/45">{x.website_url||x.contact_details||'Geen bron meegestuurd'}</p></div><form action={reviewProviderSuggestion}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="decision" value="rejected"/><button className="btn-secondary">Afwijzen</button></form><form action={reviewProviderSuggestion}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="decision" value="approved"/><button className="btn-primary">Goedkeuren</button></form></div>)}</div></section>}
    <section className="mt-9"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Alle verhuurders</h2><span className="text-sm text-white/38">{providers.length} vermeldingen</span></div><div className="mt-4 grid gap-5">{providers.map((x:any)=><form action={updateProvider} key={x.id} className="card rounded-[1.7rem] p-5 sm:p-6"><input type="hidden" name="id" value={x.id}/><div className="mb-5 flex items-center gap-3"><Building2 className="text-[#b8ff5a]"/><div><strong className="text-xl">{x.name}</strong><span className="ml-3 text-xs uppercase text-white/35">{x.provider_type}</span></div></div><div className="grid gap-4 sm:grid-cols-2"><Input name="name" label="Naam" defaultValue={x.name}/><Input name="website_url" label="Website" defaultValue={x.website_url||''}/><Input name="contact_email" label="E-mail" defaultValue={x.contact_email||''}/><Input name="contact_phone" label="Telefoon" defaultValue={x.contact_phone||''}/><Input name="swap_info_url" label="Informatie woningruil" defaultValue={x.swap_info_url||''}/><Input name="swap_application_url" label="Aanvraagformulier" defaultValue={x.swap_application_url||''}/></div><label className="label mt-4"><span>Instructies</span><textarea name="swap_instructions" defaultValue={x.swap_instructions||''} className="field min-h-24"/></label><div className="mt-4 flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="verified" defaultChecked={x.verified} className="accent-[#b8ff5a]"/><ShieldCheck size={15}/>Officieel gecontroleerd</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="active" defaultChecked={x.active} className="accent-[#b8ff5a]"/>Actief</label><button className="btn-primary ml-auto">Opslaan</button></div></form>)}</div></section>
  </main>
}
function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="label"><span>{label}</span><input {...props} className="field"/></label>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm font-bold ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
