import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { saveSearchProfile } from '@/app/housing/actions'
import { BellRing, MapPin, SlidersHorizontal } from 'lucide-react'

export const dynamic='force-dynamic'
export const metadata={title:'Mijn zoekprofiel'}
const types=[['apartment','Appartement'],['house','Eengezinswoning'],['maisonette','Maisonnette'],['studio','Studio'],['senior','Seniorenwoning'],['other','Overig']]
export default async function SearchProfile({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
  const p=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser()
  if(!user)redirect('/login?next=/search-profile')
  const {data:profile}=await s.from('search_profiles').select('*,search_locations(city),search_property_types(property_type)').eq('user_id',user.id).maybeSingle()
  const selected=new Set((profile?.search_property_types||[]).map((x:any)=>x.property_type)),locations=(profile?.search_locations||[]).map((x:any)=>x.city).filter(Boolean).join(', ')
  return <main className="mx-auto min-h-screen max-w-4xl px-4 py-12 sm:px-5"><p className="kicker">Stap 2 van 2</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Waar wil je naartoe?</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-white/52">Je zoekprofiel stuurt de matching-engine. Een match ontstaat alleen als jouw woning ook binnen de woonwensen van de andere huurder past.</p>{p.saved&&<Notice good>Zoekprofiel opgeslagen. Asorta kan nu naar wederzijdse matches zoeken.</Notice>}{p.error&&<Notice>{p.error}</Notice>}
    <form action={saveSearchProfile} className="mt-8 grid gap-6"><Section icon={<MapPin/>} title="Gewenste locaties"><label className="label"><span>Plaatsen of gemeenten *</span><input name="locations" defaultValue={locations} className="field" placeholder="Zwolle, Deventer, Raalte" required/><small className="text-white/38">Scheid meerdere locaties met een komma. Provincie- en straalzoeken volgen in een latere fase.</small></label></Section>
      <Section icon={<SlidersHorizontal/>} title="Woonwensen"><fieldset><legend className="text-sm font-black text-white/72">Woningtypen *</legend><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{types.map(([value,label])=><label key={value} className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/10 p-4 text-sm font-bold"><input type="checkbox" name="property_types" value={value} defaultChecked={selected.has(value)} className="accent-[#b8ff5a]"/>{label}</label>)}</div></fieldset><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Input name="min_rent" label="Minimale huur" type="number" min="0" defaultValue={profile?.min_rent??''}/><Input name="max_rent" label="Maximale huur" type="number" min="0" defaultValue={profile?.max_rent??''}/><Input name="min_rooms" label="Minimaal aantal kamers" type="number" min="1" defaultValue={profile?.min_rooms??''}/><Input name="min_bedrooms" label="Minimaal slaapkamers" type="number" min="0" defaultValue={profile?.min_bedrooms??''}/><Input name="min_living_area_m2" label="Minimaal woonoppervlak" type="number" min="10" defaultValue={profile?.min_living_area_m2??''}/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Check name="garden_required" label="Tuin vereist" checked={profile?.garden_required}/><Check name="balcony_required" label="Balkon vereist" checked={profile?.balcony_required}/><Check name="elevator_required" label="Lift vereist" checked={profile?.elevator_required}/><Check name="ground_floor_required" label="Begane grond vereist" checked={profile?.ground_floor_required}/><Check name="wheelchair_required" label="Rolstoeltoegankelijk" checked={profile?.wheelchair_required}/></div><label className="label mt-5"><span>Extra wensen</span><textarea name="notes" defaultValue={profile?.notes||''} className="field min-h-32" maxLength={1000} placeholder="Bijv. rustige buurt of dichtbij openbaar vervoer"/></label></Section>
      <div className="flex flex-col items-start justify-between gap-4 rounded-[2rem] border border-[#b8ff5a]/20 bg-[#b8ff5a]/[.06] p-6 sm:flex-row sm:items-center"><div className="flex gap-3"><BellRing className="mt-1 shrink-0 text-[#b8ff5a]"/><div><strong className="text-xl">Automatisch blijven zoeken</strong><p className="mt-1 text-sm text-white/48">Bij een nieuwe wederzijdse match krijg je een melding.</p></div></div><button className="btn-primary shrink-0">Zoekprofiel opslaan</button></div>
    </form>
  </main>
}
function Section({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="card rounded-[2rem] p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#b8ff5a] text-black [&_svg]:h-5 [&_svg]:w-5">{icon}</span><h2 className="text-2xl font-black">{title}</h2></div>{children}</section>}
function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="label"><span>{label}</span><input {...props} className="field"/></label>}
function Check({name,label,checked}:{name:string;label:string;checked?:boolean}){return <label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/10 p-4 text-sm font-bold"><input name={name} type="checkbox" defaultChecked={Boolean(checked)} className="accent-[#b8ff5a]"/>{label}</label>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm font-bold ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10 text-[#dcffb5]':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
