import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createHousingListing, suggestHousingProvider } from '@/app/housing/actions'
import { Camera, Home, LockKeyhole } from 'lucide-react'
import HousingProviderPicker, { type HousingProviderOption } from '@/components/HousingProviderPicker'

export const dynamic='force-dynamic'
export const metadata={title:'Woning plaatsen'}
export default async function PlaceHome({searchParams}:{searchParams:Promise<{error?:string;provider_suggested?:string}>}){
  const p=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser()
  if(!user)redirect('/login?next=/place-home')
  const [{data:providers=[]},{data:existing}]=await Promise.all([
    s.from('housing_providers').select('id,name,provider_type,verified').eq('active',true).order('name'),
    s.from('listings').select('id,status,city').eq('user_id',user.id).in('status',['draft','pending_payment','active','paused','reserved']).maybeSingle(),
  ])
  if(existing)return <main className="mx-auto min-h-screen max-w-3xl px-4 py-16 sm:px-5"><p className="kicker">Woning plaatsen</p><h1 className="mt-3 text-4xl font-black">Je hebt al een woning</h1><p className="mt-4 leading-7 text-white/50">Je woning in {existing.city} heeft status <strong className="text-white">{existing.status}</strong>. Beheer deze eerst vanuit Mijn Asorta voordat je een nieuwe woning toevoegt.</p><div className="mt-7 flex gap-3"><Link href="/account" className="btn-primary">Naar Mijn Asorta</Link>{existing.status==='pending_payment'&&<Link href={`/checkout-access?purpose=listing_activation&listing=${existing.id}`} className="btn-secondary">Activering afronden</Link>}</div></main>
  return <main className="mx-auto min-h-screen max-w-4xl px-4 py-12 sm:px-5"><div className="max-w-3xl"><p className="kicker">Stap 1 van 2</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Plaats je huurwoning</h1><p className="mt-4 text-lg leading-8 text-white/52">We hebben genoeg informatie nodig voor goede matches. Je straat, huisnummer en volledige postcode worden niet openbaar getoond.</p></div>
    {p.error&&<div className="mt-6 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-red-100">{p.error}</div>}{p.provider_suggested&&<div className="mt-6 rounded-2xl border border-[#b8ff5a]/25 bg-[#b8ff5a]/10 p-4 text-[#dcffb5]">Je verhuurder is ter controle naar ASORTA gestuurd. Kies voorlopig “Andere verhuurder” om verder te gaan.</div>}
    <details className="card mt-7 rounded-2xl"><summary className="cursor-pointer list-none p-5 font-black">Staat jouw verhuurder niet in de lijst?</summary><form action={suggestHousingProvider} className="grid gap-3 border-t border-white/10 p-5 sm:grid-cols-2"><Input name="provider_name" label="Naam verhuurder *"/><Input name="provider_website" label="Website"/><label className="label sm:col-span-2"><span>Contactgegevens of toelichting</span><input name="provider_contact" className="field"/></label><button className="btn-secondary justify-self-start sm:col-span-2">Ter controle insturen</button></form></details>
    <form action={createHousingListing} className="mt-8 grid gap-7" encType="multipart/form-data">
      <Section icon={<Home/>} title="Woninggegevens"><div className="grid gap-4 sm:grid-cols-2"><Select name="property_type" label="Woningtype *"><option value="apartment">Appartement</option><option value="house">Eengezinswoning</option><option value="maisonette">Maisonnette</option><option value="studio">Studio</option><option value="senior">Seniorenwoning</option><option value="other">Overig</option></Select><HousingProviderPicker providers={(providers || []) as HousingProviderOption[]}/><Input name="monthly_rent" label="Kale huur per maand *" type="number" min="1" step="0.01" placeholder="742"/><Input name="service_costs" label="Servicekosten per maand" type="number" min="0" step="0.01" placeholder="0"/><Input name="living_area_m2" label="Woonoppervlak (m²)" type="number" min="10" placeholder="95"/><Input name="rooms" label="Aantal kamers *" type="number" min="1" max="30"/><Input name="bedrooms" label="Aantal slaapkamers" type="number" min="0" max="20"/><Input name="floor" label="Verdieping" type="number" placeholder="0"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Check name="has_garden" label="Tuin"/><Check name="has_balcony" label="Balkon"/><Check name="has_elevator" label="Lift"/><Check name="ground_floor" label="Begane grond"/><Check name="wheelchair_accessible" label="Rolstoeltoegankelijk"/></div><label className="label mt-4"><span>Toegankelijkheid of bijzonderheden</span><input name="accessibility" className="field" placeholder="Bijv. gelijkvloers bereikbaar"/></label></Section>
      <Section icon={<LockKeyhole/>} title="Adres — blijft privé"><div className="grid gap-4 sm:grid-cols-2"><Input name="province" label="Provincie *" placeholder="Overijssel"/><Input name="municipality" label="Gemeente *" placeholder="Raalte"/><Input name="city" label="Woonplaats *" placeholder="Raalte"/><Input name="district" label="Wijk" placeholder="De Vloedkampen"/><Input name="postcode4" label="Eerste 4 cijfers postcode *" inputMode="numeric" maxLength={4} placeholder="8102"/><Input name="street" label="Straat *" autoComplete="street-address"/><Input name="house_number" label="Huisnummer + toevoeging *"/><Input name="household_size" label="Huishoudgrootte" type="number" min="1" max="20"/></div><label className="label mt-4"><span>Beschikbaar vanaf</span><input name="available_from" className="field" type="date"/></label><p className="mt-4 text-sm leading-6 text-white/42">Openbaar tonen we alleen woonplaats, wijk, provincie en de eerste vier postcodecijfers waar dat nodig is voor matching. Het volledige adres is uitsluitend voor jouw eigen dossier en een afgeronde ruil.</p></Section>
      <Section icon={<Camera/>} title="Foto's en omschrijving"><label className="label"><span>Woningfoto's * (1–8)</span><input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple required className="field file:mr-4 file:rounded-full file:border-0 file:bg-[#b8ff5a] file:px-4 file:py-2 file:font-black file:text-black"/><small className="text-white/38">JPG, PNG of WebP, maximaal 10 MB per foto. Vermijd herkenbare personen, post en documenten.</small></label><label className="label mt-4"><span>Vertel iets over je woning *</span><textarea name="description" className="field min-h-40 resize-y" minLength={30} maxLength={3000} placeholder="Beschrijf de indeling, buurt, buitenruimte en wat deze woning prettig maakt." required/></label><label className="mt-4 flex gap-3 rounded-2xl border border-white/10 p-4 text-sm leading-6 text-white/55"><input type="checkbox" required className="mt-1 accent-[#b8ff5a]"/>Ik bevestig dat ik huurder ben, toestemming heb om deze foto's te gebruiken en begrijp dat de verhuurder een woningruil uiteindelijk moet goedkeuren.</label></Section>
      <div className="flex flex-col items-start justify-between gap-4 rounded-[2rem] border border-[#b8ff5a]/20 bg-[#b8ff5a]/[.06] p-6 sm:flex-row sm:items-center"><div><strong className="text-xl">Eenmalig €2 inclusief btw</strong><p className="mt-1 text-sm text-white/48">Na opslaan ga je veilig door naar de activering. Geen abonnement.</p></div><button className="btn-primary shrink-0">Opslaan en activeren</button></div>
    </form>
  </main>
}
function Section({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="card rounded-[2rem] p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#b8ff5a] text-black [&_svg]:h-5 [&_svg]:w-5">{icon}</span><h2 className="text-2xl font-black">{title}</h2></div>{children}</section>}
function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="label"><span>{label}</span><input {...props} className="field" required={label.includes('*')||props.required}/></label>}
function Select({label,children,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <label className="label"><span>{label}</span><select {...props} className="field" required={label.includes('*')||props.required}>{children}</select></label>}
function Check({name,label}:{name:string;label:string}){return <label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/10 bg-black/15 p-4 text-sm font-bold"><input name={name} type="checkbox" className="accent-[#b8ff5a]"/>{label}</label>}
