import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { Download, ShieldCheck, Trash2 } from 'lucide-react'
import { requestAccountDeletion } from './actions'

export const dynamic='force-dynamic'
export const metadata={title:'Mijn privacygegevens',robots:{index:false,follow:false}}

export default async function PrivacyRequestPage({searchParams}:{searchParams:Promise<{requested?:string;error?:string}>}){const p=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)redirect('/login?next=/privacy-request');const{data:requestRows}=await s.from('privacy_requests').select('*').order('created_at',{ascending:false}),requests=requestRows||[];return <main className="mx-auto min-h-screen max-w-4xl px-4 py-14 sm:px-5"><p className="kicker">Privacy & account</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Jouw gegevens</h1><p className="mt-4 max-w-2xl leading-7 text-white/50">Download een kopie van je ASORTA-gegevens of vraag verwijdering van je account aan.</p>{p.requested&&<Notice good>Je verwijderverzoek is ontvangen.</Notice>}{p.error&&<Notice>{p.error}</Notice>}<div className="mt-8 grid gap-5 md:grid-cols-2"><section className="card rounded-[2rem] p-6"><Download className="text-[#b8ff5a]"/><h2 className="mt-5 text-2xl font-black">Gegevens downloaden</h2><p className="mt-3 text-sm leading-6 text-white/48">Je ontvangt een JSON-bestand met je profiel, woningen, zoekprofiel, betalingen, meldingen, matches en berichten.</p><a href="/api/privacy/export" className="btn-primary mt-6">Download mijn gegevens</a></section><section className="card rounded-[2rem] p-6"><Trash2 className="text-red-300"/><h2 className="mt-5 text-2xl font-black">Account verwijderen</h2><p className="mt-3 text-sm leading-6 text-white/48">We controleren je identiteit, lopende ruilen en wettelijke bewaarplichten voordat gegevens worden verwijderd of geanonimiseerd.</p><form action={requestAccountDeletion} className="mt-5 grid gap-3"><textarea name="reason" className="field min-h-24" placeholder="Toelichting (niet verplicht)" maxLength={1000}/><input name="confirmation" className="field" placeholder="Typ VERWIJDEREN"/><button className="btn-secondary justify-self-start text-red-100">Verwijdering aanvragen</button></form></section></div>{requests.length>0&&<section className="mt-8"><h2 className="text-2xl font-black">Eerdere verzoeken</h2><div className="mt-4 grid gap-3">{requests.map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-2xl border border-white/10 p-4 text-sm"><span>{x.request_type==='export'?'Gegevensexport':'Accountverwijdering'} · {new Date(x.created_at).toLocaleDateString('nl-NL')}</span><strong className="uppercase text-[#b8ff5a]">{x.status}</strong></div>)}</div></section>}<p className="mt-8 flex gap-2 text-xs leading-5 text-white/38"><ShieldCheck size={15} className="mt-0.5 shrink-0"/>Een verwijderverzoek wist niet automatisch gegevens die ASORTA wettelijk moet bewaren. Je ontvangt bericht over de uiteindelijke afhandeling.</p><Link href="/account" className="mt-5 inline-block text-sm font-black text-[#b8ff5a]">Terug naar Mijn ASORTA</Link></main>}
function Notice({children,good=false}:{children:React.ReactNode;good?:boolean}){return <div className={`mt-6 rounded-2xl border p-4 text-sm ${good?'border-[#b8ff5a]/25 bg-[#b8ff5a]/10':'border-red-400/25 bg-red-500/10 text-red-100'}`}>{children}</div>}
