import Link from 'next/link'
import { ArrowRightLeft, Building2, CheckCircle2, Clock3, XCircle } from 'lucide-react'
import { assertAtlasPermission } from '@/lib/atlas-auth'

export const dynamic='force-dynamic'
export const metadata={title:'Ruildossiers | Atlas',robots:{index:false,follow:false}}

export default async function SwapsPage(){
  const{admin}=await assertAtlasPermission('swaps','/atlas/swaps')
  const{data:swaps=[]}=await admin.from('swap_cases').select('*,provider_a:housing_providers!swap_cases_provider_a_id_fkey(name),provider_b:housing_providers!swap_cases_provider_b_id_fkey(name),swap_provider_status(id,user_id,status,updated_at)').order('created_at',{ascending:false}).limit(200)
  const userIds=[...new Set((swaps||[]).flatMap((x:any)=>[x.user_a_id,x.user_b_id]))]
  const listingIds=[...new Set((swaps||[]).flatMap((x:any)=>[x.listing_a_id,x.listing_b_id]))]
  const[{data:profiles=[]},{data:listings=[]}]=await Promise.all([userIds.length?admin.from('profiles').select('id,system_username,custom_display_name,display_name_mode').in('id',userIds):Promise.resolve({data:[]}),listingIds.length?admin.from('listings').select('id,city,district,property_type').in('id',listingIds):Promise.resolve({data:[]})])
  const names=new Map((profiles||[]).map((x:any)=>[x.id,x.display_name_mode==='custom'&&x.custom_display_name?x.custom_display_name:x.system_username])),homes=new Map((listings||[]).map((x:any)=>[x.id,x]))
  return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-5"><div className="flex items-end justify-between"><div><p className="kicker">Ruilproces</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Ruildossiers</h1></div><Link href="/atlas" className="btn-secondary">Terug</Link></div><div className="mt-8 grid gap-5">{(swaps||[]).map((x:any)=>{const a=homes.get(x.listing_a_id),b=homes.get(x.listing_b_id),progress=x.swap_provider_status||[];return <article key={x.id} className="card rounded-[1.7rem] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex items-center gap-2"><Status status={x.status}/><span className="font-mono text-xs text-white/30">{x.id.slice(0,8)}</span></div><h2 className="mt-4 text-2xl font-black">{a?.city||'Woning A'} <ArrowRightLeft className="mx-2 inline text-[#b8ff5a]" size={20}/> {b?.city||'Woning B'}</h2><p className="mt-2 text-sm text-white/45">{names.get(x.user_a_id)||'Ruiler A'} ↔ {names.get(x.user_b_id)||'Ruiler B'}</p></div><div className="text-sm text-white/40"><span className="block">Gestart {date(x.started_at)}</span>{x.completed_at&&<span className="mt-1 block text-[#b8ff5a]">Voltooid {date(x.completed_at)}</span>}</div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Provider name={x.provider_a?.name} row={progress.find((p:any)=>p.user_id===x.user_a_id)}/><Provider name={x.provider_b?.name} row={progress.find((p:any)=>p.user_id===x.user_b_id)}/></div><div className="mt-5 flex flex-wrap gap-3 text-xs text-white/40"><span>Woning A: {a?.district||a?.city||'—'}</span><span>Woning B: {b?.district||b?.city||'—'}</span><Link href={`/matches/${x.match_id}`} className="ml-auto font-black text-[#b8ff5a]">Open matchdossier ↗</Link></div></article>})}{!swaps?.length&&<div className="card rounded-[1.7rem] p-10 text-center"><ArrowRightLeft className="mx-auto text-[#b8ff5a]"/><h2 className="mt-4 text-2xl font-black">Nog geen ruildossiers</h2><p className="mt-2 text-white/42">Een dossier ontstaat pas nadat beide ruilers “Ja” kiezen.</p></div>}</div></main>
}
function Provider({name,row}:{name?:string;row?:any}){return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><span className="flex items-center gap-2 text-xs text-white/38"><Building2 size={14}/>{name||'Verhuurder'}</span><strong className="mt-3 flex items-center gap-2">{icon(row?.status)} {label(row?.status)}</strong><span className="mt-1 block text-xs text-white/30">{row?.updated_at?date(row.updated_at):'Nog geen update'}</span></div>}
function Status({status}:{status:string}){return <span className="status-pill">{status.replaceAll('_',' ')}</span>}
function label(v?:string){return ({not_started:'Nog niet gestart',contacted:'Contact opgenomen',submitted:'Aanvraag ingediend',pending:'In behandeling',approved:'Goedgekeurd',rejected:'Afgewezen'} as Record<string,string>)[v||'']||'Nog niet gestart'}
function icon(v?:string){if(v==='approved')return <CheckCircle2 size={17} className="text-[#b8ff5a]"/>;if(v==='rejected')return <XCircle size={17} className="text-red-300"/>;return <Clock3 size={17} className="text-amber-200"/>}
function date(v:string){return new Date(v).toLocaleString('nl-NL')}
