import Link from 'next/link'
import { BadgeEuro, Check, DatabaseZap, ShieldCheck } from 'lucide-react'
export const metadata={title:'Tarieven'}
const plans=[{title:'Woning plaatsen',price:'€2',period:'eenmalig per nieuwe plaatsing',items:['Woning 90 dagen actief','Periodiek gratis herbevestigen','Foto’s en corporatie toevoegen','Geen abonnement'],href:'/place-home'},{title:'Zoeken & matchen',price:'€5',period:'na 30 dagen gratis proberen',items:['30 dagen gratis zoeken en matches bekijken','Daarna 365 dagen volledige toegang','Reageren en privéchat na betaling','Geen automatische verlenging'],href:'/checkout-access?purpose=search_year'}]
export default function Pricing(){return <main className="mx-auto min-h-screen max-w-5xl px-4 py-16 sm:px-5"><div className="mx-auto max-w-3xl text-center"><p className="kicker">Duidelijk en laagdrempelig</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">Een klein bedrag. Geen stil abonnement.</h1><p className="mt-5 text-lg leading-8 text-white/50">Alle consumentenprijzen zijn inclusief btw. Je kiest zelf of en wanneer je opnieuw verlengt.</p></div><div className="mx-auto mt-12 grid max-w-4xl gap-5 md:grid-cols-2">{plans.map((plan,i)=><div key={plan.title} className={`rounded-[2rem] border p-7 sm:p-8 ${i===1?'border-[#b8ff5a]/45 bg-[#b8ff5a]/[.06]':'border-white/10 bg-white/[.035]'}`}><span className="text-sm font-bold text-white/45">{plan.period}</span><h2 className="mt-3 text-2xl font-black">{plan.title}</h2><strong className="mt-7 block text-6xl font-black text-[#b8ff5a]">{plan.price}</strong><div className="mt-7 grid gap-3 border-t border-white/10 pt-6">{plan.items.map(item=><span key={item} className="flex items-center gap-3 text-sm text-white/62"><Check size={17} className="text-[#b8ff5a]"/>{item}</span>)}</div><Link href={plan.href} className={`mt-7 w-full ${i===1?'btn-primary':'btn-secondary'}`}>Kies {plan.title.toLowerCase()}</Link></div>)}</div>
  <section className="mx-auto mt-12 max-w-4xl overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.035]"><div className="border-b border-white/10 p-7 sm:p-9"><p className="kicker">Waarom vragen we een bijdrage?</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Voor betrouwbare woningen en veilige matches.</h2><p className="mt-4 max-w-3xl text-base leading-7 text-white/52"><strong className="text-white">Een account maken is gratis.</strong> Je kunt daarna 30 dagen zoeken en matches bekijken. We vragen pas €5 wanneer je op een match wilt reageren of contact wilt leggen.</p></div><div className="grid gap-px bg-white/10 md:grid-cols-2"><Reason icon={<BadgeEuro/>} title="Waarom €2 voor een woning?" text="Een kleine plaatsingsbijdrage remt testadvertenties, nepwoningen en achteloos geplaatste vermeldingen. Daarmee houden we het aanbod zo actueel en serieus mogelijk. De bijdrage helpt daarnaast bij veilige foto-opslag, controle en onderhoud van woningadvertenties."/><Reason icon={<DatabaseZap/>} title="Waarom €5 voor de zoekpas?" text="Asorta vergelijkt woonwensen over en weer, bewaakt privégegevens, beheert beveiligde chat en houdt informatie over verhuurders en het ruilproces beschikbaar. De zoekpas helpt deze techniek, beveiliging en ondersteuning te onderhouden zonder automatische verlenging."/></div><div className="flex gap-3 border-t border-white/10 p-6 text-sm leading-6 text-white/45 sm:p-7"><ShieldCheck className="mt-0.5 shrink-0 text-[#b8ff5a]" size={19}/><p>De bijdrage is voor het gebruik en veilig onderhouden van Asorta. Betaling garandeert geen match of goedkeuring: beide verhuurders beslissen uiteindelijk zelf over de woningruil.</p></div></section>
  <p className="mx-auto mt-8 max-w-3xl text-center text-sm leading-6 text-white/38">Voor online diensten kan een wettelijke bedenktijd gelden. Bij het afrekenen kies je expliciet of Asorta de dienst direct mag starten. Je kunt een overeenkomst ook online <Link href="/herroepen" className="font-bold text-[#b8ff5a]">ongedaan maken</Link>.</p></main>}

function Reason({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="bg-[#080c11] p-7 sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#b8ff5a]/10 text-[#b8ff5a] [&_svg]:h-6 [&_svg]:w-6">{icon}</span><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-base leading-7 text-white/50">{text}</p></article>}
