import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { Check, CreditCard, ShieldCheck } from 'lucide-react'

export const dynamic='force-dynamic'
export const metadata={title:'Activeren'}
export default async function CheckoutAccess({searchParams}:{searchParams:Promise<{purpose?:string;listing?:string;error?:string}>}){
  const p=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser()
  if(!user)redirect(`/login?next=${encodeURIComponent(`/checkout-access?purpose=${p.purpose||'search_year'}${p.listing?`&listing=${p.listing}`:''}`)}`)
  const isListing=p.purpose==='listing_activation',amount=isListing?2:5
  if(isListing&&!p.listing)redirect('/place-home')
  return <main className="mx-auto grid min-h-[75vh] max-w-5xl items-start gap-8 px-4 py-12 sm:px-5 lg:grid-cols-[1fr_.8fr]"><section><p className="kicker">Veilig activeren</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{isListing?'Zet je woning live.':'Vind volledige matches.'}</h1><p className="mt-5 text-lg leading-8 text-white/52">{isListing?'Na betaling wordt je woning actief en kan de matching-engine aan de slag.':'Je krijgt één jaar toegang tot woningdetails, wederzijdse matches en privéchat.'}</p><div className="mt-7 grid gap-3">{(isListing?['Eenmalige betaling','Woning 90 dagen actief tot herbevestiging','Geen automatische verlenging']:['Volledige zoek- en matchtoegang','365 dagen geldig','Geen automatische verlenging']).map(x=><span key={x} className="flex items-center gap-3 text-sm font-bold text-white/62"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#b8ff5a] text-black"><Check size={14}/></span>{x}</span>)}</div></section><section className="card rounded-[2rem] p-6 sm:p-8">{p.error&&<div className="mb-5 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-sm text-red-100">{p.error}</div>}<div className="flex items-center gap-3"><CreditCard className="text-[#b8ff5a]"/><h2 className="text-2xl font-black">Betaling</h2></div><div className="mt-7 flex items-end justify-between border-y border-white/10 py-6"><div><strong>{isListing?'Woning activeren':'Zoektoegang 1 jaar'}</strong><p className="mt-1 text-sm text-white/38">Inclusief 21% btw</p></div><strong className="text-4xl">€{amount}</strong></div><form method="post" action="/api/payments/create" className="mt-6"><input type="hidden" name="purpose" value={isListing?'listing_activation':'search_year'}/>{p.listing&&<input type="hidden" name="listing_id" value={p.listing}/>}<label className="flex gap-3 rounded-2xl border border-white/10 p-4 text-sm leading-6 text-white/56"><input name="immediate_service" type="checkbox" required className="mt-1 accent-[#b8ff5a]"/><span>Ik verzoek Asorta de digitale dienst direct te starten en begrijp dat ik na volledige uitvoering mijn herroepingsrecht kan verliezen.</span></label><button className="btn-primary mt-5 w-full py-4">Ga naar veilig betalen</button></form><p className="mt-5 flex gap-2 text-xs leading-5 text-white/35"><ShieldCheck size={15} className="mt-0.5 shrink-0"/>Je betaalt via Mollie. Asorta slaat geen bank- of kaartgegevens op.</p><Link href="/terms" className="mt-3 block text-center text-xs font-bold text-white/38 hover:text-white">Voorwaarden en herroepingsinformatie</Link></section></main>
}
